// Generated by compiler-selfhost
function $claspSnapshotValue(value) {
  if (typeof globalThis.structuredClone === "function") {
    return globalThis.structuredClone(value);
  }
  return value === undefined ? undefined : JSON.parse(JSON.stringify(value));
}

function $claspExpectObject(value, path = "value") {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${path} expected an object`);
  }
  return value;
}

function $claspExpectArray(value, path = "value") {
  if (!Array.isArray(value)) {
    throw new Error(`${path} expected an array`);
  }
  return value;
}

function $claspExpectString(value, path = "value") {
  if (typeof value !== "string") {
    throw new Error(`${path} expected a string`);
  }
  return value;
}

function $claspExpectInt(value, path = "value") {
  if (!Number.isInteger(value)) {
    throw new Error(`${path} expected an integer`);
  }
  return value;
}

function $claspExpectBool(value, path = "value") {
  if (typeof value !== "boolean") {
    throw new Error(`${path} expected a boolean`);
  }
  return value;
}

const $claspBinaryMagic = Object.freeze([67, 76, 66, 49]);
const $claspTextEncoder = typeof TextEncoder === "undefined" ? null : new TextEncoder();
const $claspTextDecoder = typeof TextDecoder === "undefined" ? null : new TextDecoder();

function $claspEncodeUtf8Text(value) {
  if ($claspTextEncoder === null) {
    throw new Error("This runtime does not provide TextEncoder for binary Clasp codecs");
  }
  return $claspTextEncoder.encode($claspExpectString(value, "value"));
}

function $claspDecodeUtf8Text(bytes, path = "value") {
  if ($claspTextDecoder === null) {
    throw new Error("This runtime does not provide TextDecoder for binary Clasp codecs");
  }
  return $claspTextDecoder.decode($claspNormalizeBinaryBytes(bytes, path));
}

function $claspNormalizeBinaryBytes(value, path = "value") {
  if (value instanceof Uint8Array) {
    return value;
  }
  if (value instanceof ArrayBuffer) {
    return new Uint8Array(value);
  }
  if (ArrayBuffer.isView(value)) {
    return new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
  }
  throw new Error(`${path} expected binary bytes`);
}

function $claspWriteUint32(target, offset, value) {
  new DataView(target.buffer, target.byteOffset, target.byteLength).setUint32(offset, value, true);
}

function $claspReadUint32(source, offset, path = "value") {
  if (offset + 4 > source.byteLength) {
    throw new Error(`${path} truncated binary payload`);
  }
  return new DataView(source.buffer, source.byteOffset, source.byteLength).getUint32(offset, true);
}

function $claspFrameBinaryPayload(payload) {
  const bytes = $claspNormalizeBinaryBytes(payload, "payload");
  const frame = new Uint8Array(4 + bytes.byteLength);
  $claspWriteUint32(frame, 0, bytes.byteLength);
  frame.set(bytes, 4);
  return frame;
}

function $claspUnframeBinaryPayload(frame, path = "value") {
  const bytes = $claspNormalizeBinaryBytes(frame, path);
  const expectedLength = $claspReadUint32(bytes, 0, path);
  const payload = bytes.slice(4);
  if (payload.byteLength !== expectedLength) {
    throw new Error(`${path} expected ${expectedLength} framed bytes but received ${payload.byteLength}`);
  }
  return payload;
}

function $claspEncodeSchemaBinaryPayload(schemaContract, value) {
  const normalizedValue = schemaContract.toHost(schemaContract.fromHost(value, "value"), "value");
  const fingerprint = String(schemaContract.schema?.schemaFingerprint ?? schemaContract.type ?? schemaContract.name ?? "value");
  const fingerprintBytes = $claspEncodeUtf8Text(fingerprint);
  const payloadBytes = $claspEncodeUtf8Text(JSON.stringify(normalizedValue));
  const buffer = new Uint8Array(12 + fingerprintBytes.byteLength + payloadBytes.byteLength);
  buffer.set($claspBinaryMagic, 0);
  $claspWriteUint32(buffer, 4, fingerprintBytes.byteLength);
  $claspWriteUint32(buffer, 8, payloadBytes.byteLength);
  buffer.set(fingerprintBytes, 12);
  buffer.set(payloadBytes, 12 + fingerprintBytes.byteLength);
  return buffer;
}

function $claspDecodeSchemaBinaryPayload(schemaContract, payload, path = "value") {
  const bytes = $claspNormalizeBinaryBytes(payload, path);
  if (bytes.byteLength < 12) {
    throw new Error(`${path} expected a Clasp binary payload`);
  }
  for (let index = 0; index < $claspBinaryMagic.length; index += 1) {
    if (bytes[index] !== $claspBinaryMagic[index]) {
      throw new Error(`${path} expected a Clasp binary payload`);
    }
  }
  const fingerprintLength = $claspReadUint32(bytes, 4, path);
  const payloadLength = $claspReadUint32(bytes, 8, path);
  const payloadOffset = 12 + fingerprintLength;
  if (payloadOffset + payloadLength !== bytes.byteLength) {
    throw new Error(`${path} has an invalid Clasp binary payload length`);
  }
  const fingerprint = $claspDecodeUtf8Text(bytes.slice(12, payloadOffset), `${path}.fingerprint`);
  const expectedFingerprint = String(schemaContract.schema?.schemaFingerprint ?? schemaContract.type ?? schemaContract.name ?? "value");
  if (fingerprint !== expectedFingerprint) {
    throw new Error(`${path} expected schema fingerprint ${expectedFingerprint} but received ${fingerprint}`);
  }
  const payloadText = $claspDecodeUtf8Text(bytes.slice(payloadOffset), `${path}.payload`);
  return schemaContract.toHost(schemaContract.fromHost(JSON.parse(payloadText), path), path);
}

function $claspCreateSchemaBinaryCodec(schemaContract) {
  return Object.freeze({
    type: schemaContract.type ?? schemaContract.name ?? null,
    schemaFingerprint: String(schemaContract.schema?.schemaFingerprint ?? schemaContract.type ?? schemaContract.name ?? "value"),
    framing: "length_prefixed",
    encode(value) { return $claspEncodeSchemaBinaryPayload(schemaContract, value); },
    decode(bytes, path = "value") { return $claspDecodeSchemaBinaryPayload(schemaContract, bytes, path); },
    frame(value) { return $claspFrameBinaryPayload(this.encode(value)); },
    unframe(frame, path = "value") { return this.decode($claspUnframeBinaryPayload(frame, path), path); }
  });
}

function $claspCreateSchemaStream(contract, initial = null) {
  return Object.freeze({ kind: "clasp-schema-stream", schema: contract, initial });
}

function $claspPromptMessage(role, content) {
  return Object.freeze({
    $kind: "prompt",
    messages: Object.freeze([Object.freeze({
      role: $claspExpectString(role, "prompt.role"),
      content: $claspExpectString(content, "prompt.content")
    })])
  });
}

function $claspExpectPrompt(value, path = "value") {
  const objectValue = $claspExpectObject(value, path);
  if (objectValue.$kind !== "prompt") {
    throw new Error(`${path} expected a Prompt value`);
  }
  const messages = $claspExpectArray(objectValue.messages, `${path}.messages`).map((message, index) => {
    const messagePath = `${path}.messages[${index}]`;
    const messageObject = $claspExpectObject(message, messagePath);
    return Object.freeze({
      role: $claspExpectString(messageObject.role, `${messagePath}.role`),
      content: $claspExpectString(messageObject.content, `${messagePath}.content`)
    });
  });
  return Object.freeze({ $kind: "prompt", messages: Object.freeze(messages) });
}

function systemPrompt(content) { return $claspPromptMessage("system", content); }
function assistantPrompt(content) { return $claspPromptMessage("assistant", content); }
function userPrompt(content) { return $claspPromptMessage("user", content); }

function appendPrompt(left, right) {
  const leftPrompt = $claspExpectPrompt(left, "left");
  const rightPrompt = $claspExpectPrompt(right, "right");
  return Object.freeze({
    $kind: "prompt",
    messages: Object.freeze([...leftPrompt.messages, ...rightPrompt.messages].map((message) => Object.freeze({ role: message.role, content: message.content })))
  });
}

function promptText(value) {
  const prompt = $claspExpectPrompt(value, "value");
  return prompt.messages.map((message) => `${message.role}: ${message.content}`).join("\n\n");
}

function $claspCreateTraceCollector(seed = []) {
  const entries = Array.isArray(seed) ? seed.map((entry) => $claspSnapshotValue(entry)) : [];
  return Object.freeze({
    kind: "clasp-trace-collector",
    version: 1,
    record(entry) {
      const snapshot = $claspSnapshotValue(entry);
      entries.push(snapshot);
      return snapshot;
    },
    entries() {
      return $claspSnapshotValue(entries);
    },
    clear() {
      entries.length = 0;
      return this.entries();
    }
  });
}

function $claspMaybeRecordTrace(options = null, kind, name, action) {
  const collector = options && typeof options === "object" && options.collector && typeof options.collector.record === "function"
    ? options.collector
    : null;
  if (collector) {
    collector.record(Object.freeze({ kind, name, action, status: "ok" }));
  }
}
export const hello = "Hello from Clasp";
export function id(v) { return v; }
export const main = id(hello);
const __claspExports = Object.freeze({ hello: hello, id: id, main: main });

export const __claspSchemas = Object.freeze({  });
for (const schemaContract of Object.values(__claspSchemas)) {
  schemaContract.binary = $claspCreateSchemaBinaryCodec(schemaContract);
  schemaContract.encodeBinary = function (value) { return this.binary.encode(value); };
  schemaContract.decodeBinary = function (payload, path = "value") { return this.binary.decode(payload, path); };
  schemaContract.encodeFramedBinary = function (value) { return this.binary.frame(value); };
  schemaContract.decodeFramedBinary = function (frame, path = "value") { return this.binary.unframe(frame, path); };
  Object.freeze(schemaContract);
}

export const __claspTraceCollector = Object.freeze({
  version: 1,
  create(seed = []) { return $claspCreateTraceCollector(seed); }
});

export const __claspModule = Object.freeze({
  name: "Main",
  version: 1
});

export const __claspBindings = Object.freeze({
  kind: "clasp-generated-bindings",
  version: 1,
  module: __claspModule,
  schemas: __claspSchemas,
  traces: __claspTraceCollector
});
