{-# LANGUAGE OverloadedStrings #-}

module Weft.Emit.JavaScript
  ( emitModule
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Weft.Lower
  ( LowerDecl (..)
  , LowerExpr (..)
  , LowerMatchBranch (..)
  , LowerModule (..)
  )
import Weft.Syntax
  ( ModuleName (..)
  )

emitModule :: LowerModule -> Text
emitModule modl =
  T.unlines $
    [ "// Generated by weftc"
    , "// Source module: " <> unModuleName (lowerModuleName modl)
    ]
      <> snd (emitDecls 0 (lowerModuleDecls modl))

emitDecls :: Int -> [LowerDecl] -> (Int, [Text])
emitDecls counter decls =
  foldl emitOne (counter, []) decls
  where
    emitOne (nextCounter, rendered) decl =
      let (updatedCounter, renderedDecl) = emitDecl nextCounter decl
       in (updatedCounter, rendered <> [renderedDecl])

emitDecl :: Int -> LowerDecl -> (Int, Text)
emitDecl counter decl =
  case decl of
    LValueDecl name expr ->
      let (nextCounter, bodyText) = emitExpr counter expr
       in ( nextCounter
          , "export const "
              <> emitIdentifier name
              <> " = "
              <> bodyText
              <> ";"
          )
    LFunctionDecl name params body ->
      let (nextCounter, bodyText) = emitExpr counter body
       in ( nextCounter
          , "export function "
              <> emitIdentifier name
              <> "("
              <> T.intercalate ", " (fmap emitIdentifier params)
              <> ") { return "
              <> bodyText
              <> "; }"
          )

emitExpr :: Int -> LowerExpr -> (Int, Text)
emitExpr counter expr =
  case expr of
    LVar name ->
      (counter, emitIdentifier name)
    LInt value ->
      (counter, T.pack (show value))
    LString value ->
      (counter, emitStringLiteral value)
    LBool True ->
      (counter, "true")
    LBool False ->
      (counter, "false")
    LCall fn args ->
      let (counterAfterFn, fnText) = emitExpr counter fn
          (counterAfterArgs, argTexts) = emitExprList counterAfterFn args
       in ( counterAfterArgs
          , fnText
              <> "("
              <> T.intercalate ", " argTexts
              <> ")"
          )
    LConstruct tag fields ->
      let (nextCounter, fieldTexts) = emitExprList counter fields
          objectFields =
            T.intercalate ", " $
              ("$tag: " <> emitStringLiteral tag)
                : [ emitFieldName index <> ": " <> fieldText
                  | (index, fieldText) <- zip [(0 :: Int) ..] fieldTexts
                  ]
       in (nextCounter, "{ " <> objectFields <> " }")
    LMatch subject branches ->
      let (counterAfterSubject, subjectText) = emitExpr counter subject
          matchVar = "$match" <> T.pack (show counterAfterSubject)
          (counterAfterBranches, branchTexts) = emitMatchBranches (counterAfterSubject + 1) matchVar branches
          switchBody =
            T.unlines $
              fmap ("    " <>) branchTexts
                <> ["    default: throw new Error(\"Non-exhaustive match\");"]
       in ( counterAfterBranches
          , T.unlines
              [ "(() => {"
              , "  const " <> matchVar <> " = " <> subjectText <> ";"
              , "  switch (" <> matchVar <> ".$tag) {"
              , switchBody
              , "  }"
              , "})()"
              ]
          )

emitExprList :: Int -> [LowerExpr] -> (Int, [Text])
emitExprList counter exprs =
  foldl emitOne (counter, []) exprs
  where
    emitOne (nextCounter, rendered) expr =
      let (updatedCounter, renderedExpr) = emitExpr nextCounter expr
       in (updatedCounter, rendered <> [renderedExpr])

emitMatchBranches :: Int -> Text -> [LowerMatchBranch] -> (Int, [Text])
emitMatchBranches counter matchVar branches =
  foldl emitOne (counter, []) branches
  where
    emitOne (nextCounter, rendered) branch =
      let (updatedCounter, renderedBranch) = emitMatchBranch nextCounter matchVar branch
       in (updatedCounter, rendered <> [renderedBranch])

emitMatchBranch :: Int -> Text -> LowerMatchBranch -> (Int, Text)
emitMatchBranch counter matchVar branch =
  let bindingLines =
        [ "const "
            <> emitIdentifier binder
            <> " = "
            <> matchVar
            <> "."
            <> emitFieldName index
            <> ";"
        | (index, binder) <- zip [(0 :: Int) ..] (lowerMatchBranchBinders branch)
        ]
      (nextCounter, bodyText) = emitExpr counter (lowerMatchBranchBody branch)
      bodyLines =
        fmap ("      " <>) bindingLines
          <> ["      return " <> bodyText <> ";"]
   in ( nextCounter
      , T.unlines $
          [ "case " <> emitStringLiteral (lowerMatchBranchTag branch) <> ": {"
          ]
            <> bodyLines
            <> ["    }"]
      )

emitFieldName :: Int -> Text
emitFieldName index =
  "$" <> T.pack (show index)

emitIdentifier :: Text -> Text
emitIdentifier = id

emitStringLiteral :: Text -> Text
emitStringLiteral value =
  T.pack (show (T.unpack value))
