{-# LANGUAGE OverloadedStrings #-}

module Weft.Emit.JavaScript
  ( emitModule
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Weft.Core
  ( CoreDecl (..)
  , CoreExpr (..)
  , CoreMatchBranch (..)
  , CoreModule (..)
  , CoreParam (..)
  , CorePattern (..)
  , CorePatternBinder (..)
  )
import Weft.Syntax
  ( ConstructorDecl (..)
  , ModuleName (..)
  , TypeDecl (..)
  )

emitModule :: CoreModule -> Text
emitModule modl =
  T.unlines $
    [ "// Generated by weftc"
    , "// Source module: " <> unModuleName (coreModuleName modl)
    ]
      <> fmap emitTypeDecl (coreModuleTypeDecls modl)
      <> snd (emitDecls 0 (coreModuleDecls modl))

emitTypeDecl :: TypeDecl -> Text
emitTypeDecl typeDecl =
  T.unlines (fmap emitConstructorDecl (typeDeclConstructors typeDecl))

emitConstructorDecl :: ConstructorDecl -> Text
emitConstructorDecl constructorDecl =
  case constructorDeclFields constructorDecl of
    [] ->
      "export const "
        <> emitIdentifier (constructorDeclName constructorDecl)
        <> " = { $tag: "
        <> emitStringLiteral (constructorDeclName constructorDecl)
        <> " };"
    fieldTypes ->
      let fieldNames = fmap (("$" <>) . T.pack . show) [0 .. (length fieldTypes - 1)]
          objectFields =
            T.intercalate ", " $
              ("$tag: " <> emitStringLiteral (constructorDeclName constructorDecl))
                : fieldNames
       in "export function "
            <> emitIdentifier (constructorDeclName constructorDecl)
            <> "("
            <> T.intercalate ", " fieldNames
            <> ") { return { "
            <> objectFields
            <> " }; }"

emitDecls :: Int -> [CoreDecl] -> (Int, [Text])
emitDecls counter decls =
  foldl emitOne (counter, []) decls
  where
    emitOne (nextCounter, rendered) decl =
      let (updatedCounter, renderedDecl) = emitDecl nextCounter decl
       in (updatedCounter, rendered <> [renderedDecl])

emitDecl :: Int -> CoreDecl -> (Int, Text)
emitDecl counter decl
  | null (coreDeclParams decl) =
      let (nextCounter, bodyText) = emitExpr counter (coreDeclBody decl)
       in ( nextCounter
          , "export const "
              <> emitIdentifier (coreDeclName decl)
              <> " = "
              <> bodyText
              <> ";"
          )
  | otherwise =
      let (nextCounter, bodyText) = emitExpr counter (coreDeclBody decl)
       in ( nextCounter
          , "export function "
              <> emitIdentifier (coreDeclName decl)
              <> "("
              <> T.intercalate ", " (fmap (emitIdentifier . coreParamName) (coreDeclParams decl))
              <> ") { return "
              <> bodyText
              <> "; }"
          )

emitExpr :: Int -> CoreExpr -> (Int, Text)
emitExpr counter expr =
  case expr of
    CVar _ _ name ->
      (counter, emitIdentifier name)
    CInt _ value ->
      (counter, T.pack (show value))
    CString _ value ->
      (counter, emitStringLiteral value)
    CBool _ True ->
      (counter, "true")
    CBool _ False ->
      (counter, "false")
    CCall _ _ fn args ->
      let (counterAfterFn, fnText) = emitExpr counter fn
          (counterAfterArgs, argTexts) = emitExprList counterAfterFn args
       in ( counterAfterArgs
          , fnText
              <> "("
              <> T.intercalate ", " argTexts
              <> ")"
          )
    CMatch _ _ subject branches ->
      let (counterAfterSubject, subjectText) = emitExpr counter subject
          matchVar = "$match" <> T.pack (show counterAfterSubject)
          (counterAfterBranches, branchTexts) = emitMatchBranches (counterAfterSubject + 1) matchVar branches
          switchBody =
            T.unlines $
              fmap ("    " <>) branchTexts
                <> ["    default: throw new Error(\"Non-exhaustive match\");"]
       in ( counterAfterBranches
          , T.unlines
              [ "(() => {"
              , "  const " <> matchVar <> " = " <> subjectText <> ";"
              , "  switch (" <> matchVar <> ".$tag) {"
              , switchBody
              , "  }"
              , "})()"
              ]
          )

emitExprList :: Int -> [CoreExpr] -> (Int, [Text])
emitExprList counter exprs =
  foldl emitOne (counter, []) exprs
  where
    emitOne (nextCounter, rendered) expr =
      let (updatedCounter, renderedExpr) = emitExpr nextCounter expr
       in (updatedCounter, rendered <> [renderedExpr])

emitMatchBranches :: Int -> Text -> [CoreMatchBranch] -> (Int, [Text])
emitMatchBranches counter matchVar branches =
  foldl emitOne (counter, []) branches
  where
    emitOne (nextCounter, rendered) branch =
      let (updatedCounter, renderedBranch) = emitMatchBranch nextCounter matchVar branch
       in (updatedCounter, rendered <> [renderedBranch])

emitMatchBranch :: Int -> Text -> CoreMatchBranch -> (Int, Text)
emitMatchBranch counter matchVar branch =
  case coreMatchBranchPattern branch of
    CConstructorPattern _ constructorName binders ->
      let bindingLines =
            [ "const "
                <> emitIdentifier (corePatternBinderName binder)
                <> " = "
                <> matchVar
                <> "."
                <> emitFieldName index
                <> ";"
            | (index, binder) <- zip [(0 :: Int) ..] binders
            ]
          (nextCounter, bodyText) = emitExpr counter (coreMatchBranchBody branch)
          bodyLines =
            fmap ("      " <>) bindingLines
              <> ["      return " <> bodyText <> ";"]
       in ( nextCounter
          , T.unlines $
              [ "case " <> emitStringLiteral constructorName <> ": {"
              ]
                <> bodyLines
                <> ["    }"]
          )

emitFieldName :: Int -> Text
emitFieldName index =
  "$" <> T.pack (show index)

emitIdentifier :: Text -> Text
emitIdentifier = id

emitStringLiteral :: Text -> Text
emitStringLiteral value =
  T.pack (show (T.unpack value))
