{-# LANGUAGE OverloadedStrings #-}

module Weft.Emit.JavaScript
  ( emitModule
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Weft.Syntax
  ( Decl (..)
  , Expr (..)
  , Module (..)
  , ModuleName (..)
  )

emitModule :: Module -> Text
emitModule modl =
  T.unlines $
    [ "// Generated by weftc"
    , "// Source module: " <> unModuleName (moduleName modl)
    ]
      <> fmap emitDecl (moduleDecls modl)

emitDecl :: Decl -> Text
emitDecl decl
  | null (declParams decl) =
      "export const "
        <> emitIdentifier (declName decl)
        <> " = "
        <> emitExpr (declBody decl)
        <> ";"
  | otherwise =
      "export function "
        <> emitIdentifier (declName decl)
        <> "("
        <> T.intercalate ", " (fmap emitIdentifier (declParams decl))
        <> ") { return "
        <> emitExpr (declBody decl)
        <> "; }"

emitExpr :: Expr -> Text
emitExpr expr =
  case expr of
    EVar _ name ->
      emitIdentifier name
    EInt _ value ->
      T.pack (show value)
    EString _ value ->
      T.pack (show (T.unpack value))
    EBool _ True ->
      "true"
    EBool _ False ->
      "false"
    ECall _ fn args ->
      emitExpr fn
        <> "("
        <> T.intercalate ", " (fmap emitExpr args)
        <> ")"

emitIdentifier :: Text -> Text
emitIdentifier = id
