{-# LANGUAGE OverloadedStrings #-}

module Clasp.Emit.JavaScript
  ( emitModule
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Clasp.Lower
  ( LowerDecl (..)
  , LowerFormField (..)
  , LowerExpr (..)
  , LowerMatchBranch (..)
  , LowerModule (..)
  , LowerPageFlow (..)
  , LowerPageForm (..)
  , LowerPageLink (..)
  , LowerRecordField (..)
  , LowerRoute (..)
  , LowerRouteContract (..)
  , lowerPageFlows
  )
import Clasp.Syntax
  ( ConstructorDecl (..)
  , ForeignDecl (..)
  , ModuleName (..)
  , RecordDecl (..)
  , RecordFieldDecl (..)
  , RouteBoundaryDecl (..)
  , RouteMethod (..)
  , RoutePathDecl (..)
  , RoutePathParamDecl (..)
  , Type (..)
  , TypeDecl (..)
  )

emitModule :: LowerModule -> Text
emitModule modl =
  T.unlines $
    [ "// Generated by claspc"
    , "// Source module: " <> unModuleName (lowerModuleName modl)
    ]
      <> emitRuntimePrelude
      <> emitPrimitiveCodecHelpers
      <> emitRequestSchemaHelpers (lowerModuleTypeDecls modl) (lowerModuleRecordDecls modl)
      <> concatMap emitTypeCodecHelpers (lowerModuleTypeDecls modl)
      <> concatMap emitRecordCodecHelpers (lowerModuleRecordDecls modl)
      <> emitForeignBindings (lowerModuleTypeDecls modl) (lowerModuleRecordDecls modl) (lowerModuleForeignDecls modl)
      <> snd (emitDecls 0 (lowerModuleDecls modl))
      <> emitPageFlowArtifacts (lowerPageFlows modl)
      <> emitRoutesExport (lowerModuleTypeDecls modl) (lowerModuleRecordDecls modl) (lowerModuleRoutes modl)

emitRuntimePrelude :: [Text]
emitRuntimePrelude =
  [ ""
  , "function $claspRuntime(name) {"
  , "  const runtime = globalThis.__claspRuntime;"
  , "  if (!runtime || !(name in runtime)) {"
  , "    throw new Error(`Missing Clasp runtime binding: ${name}`);"
  , "  }"
  , "  return runtime[name];"
  , "}"
  , ""
  , "function $claspHostBinding(name) {"
  , "  const binding = $claspHostBindingMap[name];"
  , "  if (!binding) {"
  , "    throw new Error(`Missing Clasp host binding manifest: ${name}`);"
  , "  }"
  , "  return binding;"
  , "}"
  , ""
  , "function $claspCallHostBinding(name, args) {"
  , "  const binding = $claspHostBinding(name);"
  , "  const runtime = $claspRuntime(binding.runtimeName);"
  , "  const hostArgs = binding.params.map((param, index) => param.toHost(args[index]));"
  , "  return binding.returns.fromHost(runtime(...hostArgs));"
  , "}"
  , ""
  , "function $claspExpectObject(value, path) {"
  , "  if (typeof value !== \"object\" || value === null || Array.isArray(value)) {"
  , "    throw new Error(`${path} expected an object`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspBoundaryLabel(path) {"
  , "  const index = path.lastIndexOf(\".\");"
  , "  return index >= 0 ? path.slice(index + 1) : path;"
  , "}"
  , ""
  , "function $claspExpectInt(value, path) {"
  , "  if (!Number.isInteger(value)) {"
  , "    throw new Error(`${$claspBoundaryLabel(path)} must be an integer`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspExpectStr(value, path) {"
  , "  if (typeof value !== \"string\") {"
  , "    throw new Error(`${$claspBoundaryLabel(path)} must be a string`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspExpectBool(value, path) {"
  , "  if (typeof value !== \"boolean\") {"
  , "    throw new Error(`${$claspBoundaryLabel(path)} must be a boolean`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspRequireField(objectValue, fieldName, path) {"
  , "  if (!Object.prototype.hasOwnProperty.call(objectValue, fieldName)) {"
  , "    throw new Error(`${path}.${fieldName} is missing`);"
  , "  }"
  , "  return objectValue[fieldName];"
  , "}"
  , ""
  , "function $claspEscapeHtml(text) {"
  , "  return text"
  , "    .replaceAll(\"&\", \"&amp;\")"
  , "    .replaceAll(\"<\", \"&lt;\")"
  , "    .replaceAll(\">\", \"&gt;\")"
  , "    .replaceAll('\"', \"&quot;\")"
  , "    .replaceAll(\"'\", \"&#39;\");"
  , "}"
  , ""
  , "function $claspExpectView(value, path) {"
  , "  const objectValue = $claspExpectObject(value, path);"
  , "  const kind = $claspRequireField(objectValue, \"$kind\", path);"
  , "  switch (kind) {"
  , "    case \"empty\": return objectValue;"
  , "    case \"text\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"text\", path), `${path}.text`);"
  , "      return objectValue;"
  , "    case \"append\":"
  , "      $claspExpectView($claspRequireField(objectValue, \"left\", path), `${path}.left`);"
  , "      $claspExpectView($claspRequireField(objectValue, \"right\", path), `${path}.right`);"
  , "      return objectValue;"
  , "    case \"element\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"tag\", path), `${path}.tag`);"
  , "      $claspExpectView($claspRequireField(objectValue, \"child\", path), `${path}.child`);"
  , "      return objectValue;"
  , "    case \"styled\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"styleRef\", path), `${path}.styleRef`);"
  , "      $claspExpectView($claspRequireField(objectValue, \"child\", path), `${path}.child`);"
  , "      return objectValue;"
  , "    case \"link\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"href\", path), `${path}.href`);"
  , "      $claspExpectView($claspRequireField(objectValue, \"child\", path), `${path}.child`);"
  , "      return objectValue;"
  , "    case \"form\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"method\", path), `${path}.method`);"
  , "      $claspExpectStr($claspRequireField(objectValue, \"action\", path), `${path}.action`);"
  , "      $claspExpectView($claspRequireField(objectValue, \"child\", path), `${path}.child`);"
  , "      return objectValue;"
  , "    case \"input\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"fieldName\", path), `${path}.fieldName`);"
  , "      $claspExpectStr($claspRequireField(objectValue, \"inputKind\", path), `${path}.inputKind`);"
  , "      $claspExpectStr($claspRequireField(objectValue, \"value\", path), `${path}.value`);"
  , "      return objectValue;"
  , "    case \"submit\":"
  , "      $claspExpectStr($claspRequireField(objectValue, \"label\", path), `${path}.label`);"
  , "      return objectValue;"
  , "    default:"
  , "      throw new Error(`${path} expected a View value`);"
  , "  }"
  , "}"
  , ""
  , "function $claspExpectPage(value, path = \"value\") {"
  , "  const objectValue = $claspExpectObject(value, path);"
  , "  if ($claspRequireField(objectValue, \"$kind\", path) !== \"page\") {"
  , "    throw new Error(`${path} expected a Page value`);"
  , "  }"
  , "  $claspExpectStr($claspRequireField(objectValue, \"title\", path), `${path}.title`);"
  , "  $claspExpectView($claspRequireField(objectValue, \"body\", path), `${path}.body`);"
  , "  return objectValue;"
  , "}"
  , ""
  , "function $claspExpectRedirect(value, path = \"value\") {"
  , "  const objectValue = $claspExpectObject(value, path);"
  , "  if ($claspRequireField(objectValue, \"$kind\", path) !== \"redirect\") {"
  , "    throw new Error(`${path} expected a Redirect value`);"
  , "  }"
  , "  const location = $claspExpectStr($claspRequireField(objectValue, \"location\", path), `${path}.location`);"
  , "  const status = $claspExpectInt(objectValue.status ?? 303, `${path}.status`);"
  , "  return { $kind: \"redirect\", location, status };"
  , "}"
  , ""
  , "function $prepare_Redirect(value) {"
  , "  return $claspExpectRedirect(value, \"value\");"
  , "}"
  , ""
  , "function $claspRenderFlowAttrs(contract, flowKind) {"
  , "  if (!contract || typeof contract !== \"object\") {"
  , "    return ` data-clasp-flow=\"${$claspEscapeHtml(flowKind)}\"`;"
  , "  }"
  , "  const routeName = typeof contract.routeName === \"string\" ? contract.routeName : \"\";"
  , "  const routeId = typeof contract.routeId === \"string\" ? contract.routeId : \"\";"
  , "  const routeMethod = typeof contract.method === \"string\" ? contract.method : \"\";"
  , "  const routePath = typeof contract.path === \"string\" ? contract.path : \"\";"
  , "  const requestType = typeof contract.requestType === \"string\" ? contract.requestType : \"\";"
  , "  const responseType = typeof contract.responseType === \"string\" ? contract.responseType : \"\";"
  , "  const responseKind = typeof contract.responseKind === \"string\" ? contract.responseKind : \"\";"
  , "  return ` data-clasp-flow=\"${$claspEscapeHtml(flowKind)}\" data-clasp-route=\"${$claspEscapeHtml(routeName)}\" data-clasp-route-id=\"${$claspEscapeHtml(routeId)}\" data-clasp-method=\"${$claspEscapeHtml(routeMethod)}\" data-clasp-path=\"${$claspEscapeHtml(routePath)}\" data-clasp-request-type=\"${$claspEscapeHtml(requestType)}\" data-clasp-response-type=\"${$claspEscapeHtml(responseType)}\" data-clasp-response-kind=\"${$claspEscapeHtml(responseKind)}\"`;"
  , "}"
  , ""
  , "function $claspRenderView(view) {"
  , "  const checkedView = $claspExpectView(view, \"view\");"
  , "  switch (checkedView.$kind) {"
  , "    case \"empty\":"
  , "      return \"\";"
  , "    case \"text\":"
  , "      return $claspEscapeHtml(checkedView.text);"
  , "    case \"append\":"
  , "      return $claspRenderView(checkedView.left) + $claspRenderView(checkedView.right);"
  , "    case \"element\":"
  , "      return `<${checkedView.tag}>${$claspRenderView(checkedView.child)}</${checkedView.tag}>`;"
  , "    case \"styled\":"
  , "      return `<div data-clasp-style=${JSON.stringify($claspExpectStr(checkedView.styleRef, \"view.styleRef\"))}>${$claspRenderView(checkedView.child)}</div>`;"
  , "    case \"link\":"
  , "      return `<a${$claspRenderFlowAttrs(checkedView.contract, \"navigation\")} href=\"${$claspEscapeHtml($claspExpectStr(checkedView.href, \"view.href\"))}\">${$claspRenderView(checkedView.child)}</a>`;"
  , "    case \"form\":"
  , "      return `<form${$claspRenderFlowAttrs(checkedView.contract, \"action\")} method=\"${$claspEscapeHtml($claspExpectStr(checkedView.method, \"view.method\"))}\" action=\"${$claspEscapeHtml($claspExpectStr(checkedView.action, \"view.action\"))}\">${$claspRenderView(checkedView.child)}</form>`;"
  , "    case \"input\":"
  , "      return `<input name=\"${$claspEscapeHtml($claspExpectStr(checkedView.fieldName, \"view.fieldName\"))}\" type=\"${$claspEscapeHtml($claspExpectStr(checkedView.inputKind, \"view.inputKind\"))}\" value=\"${$claspEscapeHtml($claspExpectStr(checkedView.value, \"view.value\"))}\">`;"
  , "    case \"submit\":"
  , "      return `<button type=\"submit\">${$claspEscapeHtml($claspExpectStr(checkedView.label, \"view.label\"))}</button>`;"
  , "    default:"
  , "      throw new Error(\"Unknown View node\");"
  , "  }"
  , "}"
  , ""
  , "function $render_Page(value) {"
  , "  const page = $claspExpectPage(value);"
  , "  return \"<!DOCTYPE html><html><head><meta charset=\\\"utf-8\\\"><title>\" + $claspEscapeHtml(page.title) + \"</title></head><body>\" + $claspRenderView(page.body) + \"</body></html>\";"
  , "}"
  , ""
  ]

emitPrimitiveCodecHelpers :: [Text]
emitPrimitiveCodecHelpers =
  [ "function $decode_Int(jsonText) { return $claspExpectInt(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Int(value) { return JSON.stringify($claspExpectInt(value, \"value\")); }"
  , "function $decode_Str(jsonText) { return $claspExpectStr(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Str(value) { return JSON.stringify($claspExpectStr(value, \"value\")); }"
  , "function $decode_Bool(jsonText) { return $claspExpectBool(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Bool(value) { return JSON.stringify($claspExpectBool(value, \"value\")); }"
  , "function $decode_Redirect(jsonText) { return $claspExpectRedirect(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Redirect(value) { return JSON.stringify($claspExpectRedirect(value, \"value\")); }"
  , ""
  ]

emitRequestSchemaHelpers :: [TypeDecl] -> [RecordDecl] -> [Text]
emitRequestSchemaHelpers typeDecls recordDecls =
  [ "const $claspSchema_Int = { kind: \"int\" };"
  , "const $claspSchema_Str = { kind: \"str\" };"
  , "const $claspSchema_Bool = { kind: \"bool\" };"
  ]
    <> concatMap emitTypeSchema typeDecls
    <> concatMap emitRecordSchema recordDecls
    <> [""]
  where
    emitTypeSchema typeDecl
      | isJsonEnumTypeDecl typeDecl =
          [ "const $claspSchema_" <> typeDeclName typeDecl <> " = { kind: \"enum\", name: " <> emitStringLiteral (typeDeclName typeDecl) <> " };"
          ]
      | otherwise =
          []

    emitRecordSchema recordDecl =
      [ "const $claspSchema_" <> recordDeclName recordDecl <> " = {"
      , "  kind: \"record\","
      , "  name: " <> emitStringLiteral (recordDeclName recordDecl) <> ","
      , "  classificationPolicy: " <> emitOptionalText (recordDeclProjectionPolicy recordDecl) <> ","
      , "  projectionSource: " <> emitOptionalText (recordDeclProjectionSource recordDecl) <> ","
      , "  fields: {"
      ]
        <> fmap emitRecordFieldSchema (recordDeclFields recordDecl)
        <> [ "  }"
           , "};"
           ]

    emitRecordFieldSchema fieldDecl =
      "    "
        <> recordFieldDeclName fieldDecl
        <> ": {"
        <> " schema: "
        <> emitRequestSchemaRef (recordFieldDeclType fieldDecl)
        <> ", classification: "
        <> emitStringLiteral (recordFieldDeclClassification fieldDecl)
        <> " },"

    emitRequestSchemaRef typ =
      case typ of
        TInt ->
          "$claspSchema_Int"
        TStr ->
          "$claspSchema_Str"
        TBool ->
          "$claspSchema_Bool"
        TNamed name ->
          if any ((== name) . typeDeclName) typeDecls || any ((== name) . recordDeclName) recordDecls
            then "$claspSchema_" <> name
            else "null"
        TFunction _ _ ->
          "null"

emitOptionalText :: Maybe Text -> Text
emitOptionalText maybeText =
  case maybeText of
    Just value ->
      emitStringLiteral value
    Nothing ->
      "null"

emitTypeCodecHelpers :: TypeDecl -> [Text]
emitTypeCodecHelpers typeDecl
  | isJsonEnumTypeDecl typeDecl =
      [ "function " <> validateName <> "(value, path = \"value\") {"
      , "  switch (value) {"
      ]
        <> concatMap emitValidateCase constructors
        <> [ "    default: throw new Error(`${$claspBoundaryLabel(path)} must be one of: " <> expectedValues <> "`);"
           , "  }"
           , "}"
           , "function " <> validateInternalName <> "(value, path = \"value\") {"
           , "  const tag = typeof value === \"object\" && value !== null ? value.$tag : null;"
           , "  switch (tag) {"
           ]
        <> concatMap emitValidateInternalCase constructors
        <> [ "    default: throw new Error(`${path} expected a " <> typeDeclName typeDecl <> " value`);"
           , "  }"
           , "}"
           , "function " <> serializeName <> "(value, path = \"value\") {"
           , "  const tag = typeof value === \"object\" && value !== null ? value.$tag : null;"
           , "  switch (tag) {"
           ]
        <> concatMap emitSerializeCase constructors
        <> [ "    default: throw new Error(`${path} expected a " <> typeDeclName typeDecl <> " value`);"
           , "  }"
           , "}"
           , "function " <> decodeName <> "(jsonText) { return " <> validateName <> "(JSON.parse(jsonText), \"value\"); }"
           , "function " <> encodeName <> "(value) { return JSON.stringify(" <> serializeName <> "(value, \"value\")); }"
           , ""
           ]
  | otherwise =
      []
  where
    constructors = typeDeclConstructors typeDecl
    expectedValues = T.intercalate ", " (fmap constructorWireValue constructors)
    validateName = "$validate_" <> typeDeclName typeDecl
    validateInternalName = "$validateInternal_" <> typeDeclName typeDecl
    serializeName = "$serialize_" <> typeDeclName typeDecl
    decodeName = "$decode_" <> typeDeclName typeDecl
    encodeName = "$encode_" <> typeDeclName typeDecl

    emitValidateCase constructorDecl =
      [ "    case "
          <> emitStringLiteral (constructorWireValue constructorDecl)
          <> ": return "
          <> emitIdentifier (constructorDeclName constructorDecl)
          <> ";"
      ]

    emitValidateInternalCase constructorDecl =
      [ "    case "
          <> emitStringLiteral (constructorDeclName constructorDecl)
          <> ": return value;"
      ]

    emitSerializeCase constructorDecl =
      [ "    case "
          <> emitStringLiteral (constructorDeclName constructorDecl)
          <> ": return "
          <> emitStringLiteral (constructorWireValue constructorDecl)
          <> ";"
      ]

emitRecordCodecHelpers :: RecordDecl -> [Text]
emitRecordCodecHelpers recordDecl =
  [ "function " <> validateName <> "(value, path = \"value\") {"
  , "  const objectValue = $claspExpectObject(value, path);"
  ]
    <> concatMap emitValidateField (recordDeclFields recordDecl)
    <> [ "  return { " <> T.intercalate ", " (fmap (\fieldDecl -> recordFieldDeclName fieldDecl <> ": " <> recordFieldDeclName fieldDecl) (recordDeclFields recordDecl)) <> " };"
       , "}"
       , "function " <> validateInternalName <> "(value, path = \"value\") {"
       , "  const objectValue = $claspExpectObject(value, path);"
       ]
    <> concatMap emitValidateInternalField (recordDeclFields recordDecl)
    <> [ "  return { " <> T.intercalate ", " (fmap (\fieldDecl -> recordFieldDeclName fieldDecl <> ": " <> recordFieldDeclName fieldDecl) (recordDeclFields recordDecl)) <> " };"
       , "}"
       , "function " <> serializeName <> "(value) {"
       ]
    <> concatMap emitSerializeField (recordDeclFields recordDecl)
    <> [ "  return { " <> T.intercalate ", " (fmap (\fieldDecl -> recordFieldDeclName fieldDecl <> ": " <> recordFieldDeclName fieldDecl) (recordDeclFields recordDecl)) <> " };"
       , "}"
       , "function " <> decodeName <> "(jsonText) { return " <> validateName <> "(JSON.parse(jsonText), \"value\"); }"
       , "function " <> encodeName <> "(value) { return JSON.stringify(" <> serializeName <> "(" <> validateInternalName <> "(value, \"value\"))); }"
       , ""
       ]
  where
    validateName = "$validate_" <> recordDeclName recordDecl
    validateInternalName = "$validateInternal_" <> recordDeclName recordDecl
    serializeName = "$serialize_" <> recordDeclName recordDecl
    decodeName = "$decode_" <> recordDeclName recordDecl
    encodeName = "$encode_" <> recordDeclName recordDecl

    emitValidateField fieldDecl =
      let fieldName = recordFieldDeclName fieldDecl
          fieldPath = "path + " <> emitStringLiteral ("." <> fieldName)
       in [ "  const " <> fieldName <> "Value = objectValue[" <> emitStringLiteral fieldName <> "];"
          , "  const " <> fieldName <> " = " <> emitValidator (recordFieldDeclType fieldDecl) (fieldName <> "Value") fieldPath <> ";"
          ]

    emitValidateInternalField fieldDecl =
      let fieldName = recordFieldDeclName fieldDecl
          fieldPath = "path + " <> emitStringLiteral ("." <> fieldName)
       in [ "  const " <> fieldName <> "Value = $claspRequireField(objectValue, " <> emitStringLiteral fieldName <> ", path);"
          , "  const " <> fieldName <> " = " <> emitInternalValidator (recordFieldDeclType fieldDecl) (fieldName <> "Value") fieldPath <> ";"
          ]

    emitSerializeField fieldDecl =
      let fieldName = recordFieldDeclName fieldDecl
       in [ "  const " <> fieldName <> " = " <> emitSerializer (recordFieldDeclType fieldDecl) ("value." <> fieldName) <> ";" ]

emitForeignBindings :: [TypeDecl] -> [RecordDecl] -> [ForeignDecl] -> [Text]
emitForeignBindings typeDecls recordDecls foreignDecls =
  emitHostBindingManifest
    <> fmap emitForeignBinding foreignDecls
    <> [""]
  where
    emitHostBindingManifest
      | null foreignDecls =
          [ "export const __claspHostBindings = [];"
          , "const $claspHostBindingMap = {};"
          ]
      | otherwise =
          [ "export const __claspHostBindings = ["
          ]
            <> concatMap emitHostBindingEntry foreignDecls
            <> [ "];"
               , "const $claspHostBindingMap = Object.fromEntries(__claspHostBindings.map((binding) => [binding.name, binding]));"
               ]

    emitHostBindingEntry foreignDecl =
      let (paramTypes, returnType) = splitFunctionType (foreignDeclType foreignDecl)
       in [ "  {"
          , "    name: " <> emitStringLiteral (foreignDeclName foreignDecl) <> ","
          , "    runtimeName: " <> emitStringLiteral (foreignDeclRuntimeName foreignDecl) <> ","
          , "    params: ["
          ]
            <> concat
              [ [ "      {"
                , "        index: " <> T.pack (show index) <> ","
                , "        type: " <> emitStringLiteral (renderTypeName paramType) <> ","
                , "        schema: " <> emitSchemaRef typeDecls recordDecls paramType <> ","
                , "        toHost(value) { return " <> emitHostSerializer paramType "value" "\"value\"" <> "; }"
                , "      },"
                ]
              | (index, paramType) <- zip [(0 :: Int) ..] paramTypes
              ]
            <> [ "    ],"
               , "    returns: {"
               , "      type: " <> emitStringLiteral (renderTypeName returnType) <> ","
               , "      schema: " <> emitSchemaRef typeDecls recordDecls returnType <> ","
               , "      fromHost(value) { return " <> emitHostDeserializer returnType "value" "\"result\"" <> "; }"
               , "    }"
               , "  },"
               ]

    emitForeignBinding foreignDecl =
      let params = foreignParams (foreignDeclType foreignDecl)
       in "function "
            <> emitIdentifier (foreignDeclName foreignDecl)
            <> "("
            <> T.intercalate ", " params
            <> ") { return $claspCallHostBinding("
            <> emitStringLiteral (foreignDeclName foreignDecl)
            <> ", ["
            <> T.intercalate ", " params
            <> "]); }"

emitPageFlowArtifacts :: [LowerPageFlow] -> [Text]
emitPageFlowArtifacts pageFlows =
  [ "export const __claspUiGraph = ["
  ]
    <> concatMap emitUiPage pageFlows
    <> [ "];"
       , "export const __claspNavigationGraph = ["
       ]
    <> concatMap emitNavigationEdges pageFlows
    <> [ "];"
       , "export const __claspActionGraph = ["
       ]
    <> concatMap emitActionEdges pageFlows
    <> [ "];"
       ]
  where
    emitUiPage pageFlow =
      [ "  {"
      , "    routeName: " <> emitStringLiteral (lowerPageFlowRouteName pageFlow) <> ","
      , "    routeId: " <> emitStringLiteral (lowerPageFlowRouteIdentity pageFlow) <> ","
      , "    path: " <> emitStringLiteral (lowerPageFlowPath pageFlow) <> ","
      , "    handler: " <> emitStringLiteral (lowerPageFlowHandlerName pageFlow) <> ","
      , "    title: " <> emitStringLiteral (lowerPageFlowTitle pageFlow) <> ","
      , "    texts: [" <> T.intercalate ", " (fmap emitStringLiteral (lowerPageFlowTexts pageFlow)) <> "],"
      , "    links: [" <> T.intercalate ", " (fmap emitPageLink (lowerPageFlowLinks pageFlow)) <> "],"
      , "    forms: [" <> T.intercalate ", " (fmap emitPageForm (lowerPageFlowForms pageFlow)) <> "]"
      , "  },"
      ]

    emitNavigationEdges pageFlow =
      fmap (emitNavigationEdge pageFlow) (lowerPageFlowLinks pageFlow)

    emitNavigationEdge pageFlow pageLink =
      "  { sourceRoute: "
        <> emitStringLiteral (lowerPageFlowRouteName pageFlow)
        <> ", sourceRouteId: "
        <> emitStringLiteral (lowerPageFlowRouteIdentity pageFlow)
        <> ", sourcePath: "
        <> emitStringLiteral (lowerPageFlowPath pageFlow)
        <> ", targetRoute: "
        <> emitStringLiteral (lowerPageLinkRouteName pageLink)
        <> ", targetRouteId: "
        <> emitStringLiteral (lowerPageLinkRouteIdentity pageLink)
        <> ", targetPath: "
        <> emitStringLiteral (lowerPageLinkPath pageLink)
        <> ", href: "
        <> emitStringLiteral (lowerPageLinkHref pageLink)
        <> ", label: "
        <> emitStringLiteral (lowerPageLinkLabel pageLink)
        <> " },"

    emitActionEdges pageFlow =
      fmap (emitActionEdge pageFlow) (lowerPageFlowForms pageFlow)

    emitActionEdge pageFlow pageForm =
      "  { sourceRoute: "
        <> emitStringLiteral (lowerPageFlowRouteName pageFlow)
        <> ", sourceRouteId: "
        <> emitStringLiteral (lowerPageFlowRouteIdentity pageFlow)
        <> ", sourcePath: "
        <> emitStringLiteral (lowerPageFlowPath pageFlow)
        <> ", actionRoute: "
        <> emitStringLiteral (lowerPageFormRouteName pageForm)
        <> ", actionRouteId: "
        <> emitStringLiteral (lowerPageFormRouteIdentity pageForm)
        <> ", actionPath: "
        <> emitStringLiteral (lowerPageFormPath pageForm)
        <> ", method: "
        <> emitStringLiteral (lowerPageFormMethod pageForm)
        <> ", action: "
        <> emitStringLiteral (lowerPageFormAction pageForm)
        <> ", requestType: "
        <> emitStringLiteral (lowerPageFormRequestType pageForm)
        <> ", responseType: "
        <> emitStringLiteral (lowerPageFormResponseType pageForm)
        <> ", responseKind: "
        <> emitStringLiteral (lowerPageFormResponseKind pageForm)
        <> ", fields: ["
        <> T.intercalate ", " (fmap emitFormField (lowerPageFormFields pageForm))
        <> "], submitLabels: ["
        <> T.intercalate ", " (fmap emitStringLiteral (lowerPageFormSubmitLabels pageForm))
        <> "] },"

emitPageLink :: LowerPageLink -> Text
emitPageLink pageLink =
  "{ routeName: "
    <> emitStringLiteral (lowerPageLinkRouteName pageLink)
    <> ", routeId: "
    <> emitStringLiteral (lowerPageLinkRouteIdentity pageLink)
    <> ", path: "
    <> emitStringLiteral (lowerPageLinkPath pageLink)
    <> ", href: "
    <> emitStringLiteral (lowerPageLinkHref pageLink)
    <> ", label: "
    <> emitStringLiteral (lowerPageLinkLabel pageLink)
    <> " }"

emitPageForm :: LowerPageForm -> Text
emitPageForm pageForm =
  "{ routeName: "
    <> emitStringLiteral (lowerPageFormRouteName pageForm)
    <> ", routeId: "
    <> emitStringLiteral (lowerPageFormRouteIdentity pageForm)
    <> ", path: "
    <> emitStringLiteral (lowerPageFormPath pageForm)
    <> ", method: "
    <> emitStringLiteral (lowerPageFormMethod pageForm)
    <> ", action: "
    <> emitStringLiteral (lowerPageFormAction pageForm)
    <> ", requestType: "
    <> emitStringLiteral (lowerPageFormRequestType pageForm)
    <> ", responseType: "
    <> emitStringLiteral (lowerPageFormResponseType pageForm)
    <> ", responseKind: "
    <> emitStringLiteral (lowerPageFormResponseKind pageForm)
    <> ", fields: ["
    <> T.intercalate ", " (fmap emitFormField (lowerPageFormFields pageForm))
    <> "], submitLabels: ["
    <> T.intercalate ", " (fmap emitStringLiteral (lowerPageFormSubmitLabels pageForm))
    <> "] }"

emitFormField :: LowerFormField -> Text
emitFormField formField =
  "{ name: "
    <> emitStringLiteral (lowerFormFieldName formField)
    <> ", inputKind: "
    <> emitStringLiteral (lowerFormFieldInputKind formField)
    <> ", label: "
    <> emitOptionalText (lowerFormFieldLabel formField)
    <> ", value: "
    <> emitStringLiteral (lowerFormFieldValue formField)
    <> " }"

foreignParams :: Type -> [Text]
foreignParams typ =
  case typ of
    TFunction args _ ->
      fmap (("$" <>) . T.pack . show) [(0 :: Int) .. length args - 1]
    _ ->
      []

splitFunctionType :: Type -> ([Type], Type)
splitFunctionType typ =
  case typ of
    TFunction args result ->
      (args, result)
    _ ->
      ([], typ)

emitRoutesExport :: [TypeDecl] -> [RecordDecl] -> [LowerRoute] -> [Text]
emitRoutesExport typeDecls recordDecls routes =
  [ "export const __claspRoutes = ["
  ]
    <> concatMap emitRoute routes
    <> [ "];" ]
  where
    emitRoute route =
      let responseEncoder =
            case lowerRouteResponseTypeName route of
              "Page" ->
                "$render_Page"
              "Redirect" ->
                "$prepare_Redirect"
              responseTypeName ->
                "$encode_" <> responseTypeName
          responseKind =
            case lowerRouteResponseTypeName route of
              "Page" -> "page"
              "Redirect" -> "redirect"
              _ -> "json"
       in
      [ "  {"
      , "    name: " <> emitStringLiteral (lowerRouteName route) <> ","
      , "    id: " <> emitStringLiteral (lowerRouteIdentity route) <> ","
      , "    method: " <> emitStringLiteral (emitRouteMethod (lowerRouteMethod route)) <> ","
      , "    path: " <> emitStringLiteral (lowerRoutePath route) <> ","
      , "    pathDecl: " <> emitRoutePathDecl (lowerRoutePathDecl route) <> ","
      , "    queryDecl: " <> emitRouteBoundaryDecl typeDecls recordDecls (lowerRouteQueryDecl route) <> ","
      , "    formDecl: " <> emitRouteBoundaryDecl typeDecls recordDecls (lowerRouteFormDecl route) <> ","
      , "    bodyDecl: " <> emitRouteBoundaryDecl typeDecls recordDecls (lowerRouteBodyDecl route) <> ","
      , "    requestType: " <> emitStringLiteral (lowerRouteRequestTypeName route) <> ","
      , "    requestSchema: " <> emitRouteRequestSchemaFor typeDecls recordDecls (lowerRouteRequestTypeName route) <> ","
      , "    responseType: " <> emitStringLiteral (lowerRouteResponseTypeName route) <> ","
      , "    responseDecl: " <> emitRouteBoundaryDecl typeDecls recordDecls (Just (lowerRouteResponseDecl route)) <> ","
      , "    responseKind: " <> emitStringLiteral responseKind <> ","
      , "    handler: " <> emitIdentifier (lowerRouteHandlerName route) <> ","
      , "    decodeRequest: $decode_" <> lowerRouteRequestTypeName route <> ","
      , "    encodeResponse: " <> responseEncoder
      , "  },"
      ]

emitRouteMethod :: RouteMethod -> Text
emitRouteMethod routeMethod =
  case routeMethod of
    RouteGet ->
      "GET"
    RoutePost ->
      "POST"

emitRoutePathDecl :: RoutePathDecl -> Text
emitRoutePathDecl pathDecl =
  "{ pattern: "
    <> emitStringLiteral (routePathDeclPattern pathDecl)
    <> ", params: ["
    <> T.intercalate ", " (fmap emitRoutePathParamDecl (routePathDeclParams pathDecl))
    <> "] }"

emitRoutePathParamDecl :: RoutePathParamDecl -> Text
emitRoutePathParamDecl pathParam =
  "{ name: "
    <> emitStringLiteral (routePathParamDeclName pathParam)
    <> ", type: "
    <> emitStringLiteral (routePathParamDeclType pathParam)
    <> " }"

emitRouteBoundaryDecl :: [TypeDecl] -> [RecordDecl] -> Maybe RouteBoundaryDecl -> Text
emitRouteBoundaryDecl _ _ Nothing = "null"
emitRouteBoundaryDecl typeDecls recordDecls (Just boundary) =
  "{ type: "
    <> emitStringLiteral (routeBoundaryDeclType boundary)
    <> ", schema: "
    <> emitRouteRequestSchemaFor typeDecls recordDecls (routeBoundaryDeclType boundary)
    <> " }"

emitRouteRequestSchemaFor :: [TypeDecl] -> [RecordDecl] -> Text -> Text
emitRouteRequestSchemaFor typeDecls recordDecls typeName
  | typeName == "Int" || typeName == "Str" || typeName == "Bool" =
      "$claspSchema_" <> typeName
  | any ((== typeName) . typeDeclName) typeDecls || any ((== typeName) . recordDeclName) recordDecls =
      "$claspSchema_" <> typeName
  | otherwise =
      "null"

emitValidator :: Type -> Text -> Text -> Text
emitValidator typ valueRef pathRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", " <> pathRef <> ")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", " <> pathRef <> ")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", " <> pathRef <> ")"
    TNamed name ->
      "$validate_" <> name <> "(" <> valueRef <> ", " <> pathRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitInternalValidator :: Type -> Text -> Text -> Text
emitInternalValidator typ valueRef pathRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", " <> pathRef <> ")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", " <> pathRef <> ")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", " <> pathRef <> ")"
    TNamed name ->
      "$validateInternal_" <> name <> "(" <> valueRef <> ", " <> pathRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitSerializer :: Type -> Text -> Text
emitSerializer typ valueRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", \"value\")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", \"value\")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", \"value\")"
    TNamed name ->
      "$serialize_" <> name <> "(" <> valueRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitHostSerializer :: Type -> Text -> Text -> Text
emitHostSerializer typ valueRef pathRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", " <> pathRef <> ")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", " <> pathRef <> ")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", " <> pathRef <> ")"
    TNamed name ->
      "$serialize_" <> name <> "($validateInternal_" <> name <> "(" <> valueRef <> ", " <> pathRef <> "))"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitHostDeserializer :: Type -> Text -> Text -> Text
emitHostDeserializer typ valueRef pathRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", " <> pathRef <> ")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", " <> pathRef <> ")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", " <> pathRef <> ")"
    TNamed name ->
      "$validate_" <> name <> "(" <> valueRef <> ", " <> pathRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitSchemaRef :: [TypeDecl] -> [RecordDecl] -> Type -> Text
emitSchemaRef typeDecls recordDecls typ =
  case typ of
    TInt ->
      "$claspSchema_Int"
    TStr ->
      "$claspSchema_Str"
    TBool ->
      "$claspSchema_Bool"
    TNamed name ->
      if any ((== name) . typeDeclName) typeDecls || any ((== name) . recordDeclName) recordDecls
        then "$claspSchema_" <> name
        else "null"
    TFunction _ _ ->
      "null"

renderTypeName :: Type -> Text
renderTypeName typ =
  case typ of
    TInt ->
      "Int"
    TStr ->
      "Str"
    TBool ->
      "Bool"
    TNamed name ->
      name
    TFunction args result ->
      T.intercalate " -> " (fmap renderTypeName args <> [renderTypeName result])

isJsonEnumTypeDecl :: TypeDecl -> Bool
isJsonEnumTypeDecl typeDecl =
  all (null . constructorDeclFields) (typeDeclConstructors typeDecl)

constructorWireValue :: ConstructorDecl -> Text
constructorWireValue constructorDecl =
  T.toLower (constructorDeclName constructorDecl)

emitDecls :: Int -> [LowerDecl] -> (Int, [Text])
emitDecls counter decls =
  foldl emitOne (counter, []) decls
  where
    emitOne (nextCounter, rendered) decl =
      let (updatedCounter, renderedDecl) = emitDecl nextCounter decl
       in (updatedCounter, rendered <> [renderedDecl])

emitDecl :: Int -> LowerDecl -> (Int, Text)
emitDecl counter decl =
  case decl of
    LValueDecl name expr ->
      let (nextCounter, bodyText) = emitExpr counter expr
       in ( nextCounter
          , "export const "
              <> emitIdentifier name
              <> " = "
              <> bodyText
              <> ";"
          )
    LFunctionDecl name params body ->
      let (nextCounter, bodyText) = emitExpr counter body
       in ( nextCounter
          , "export function "
              <> emitIdentifier name
              <> "("
              <> T.intercalate ", " (fmap emitIdentifier params)
              <> ") { return "
              <> bodyText
              <> "; }"
          )

emitExpr :: Int -> LowerExpr -> (Int, Text)
emitExpr counter expr =
  case expr of
    LVar name ->
      (counter, emitIdentifier name)
    LInt value ->
      (counter, T.pack (show value))
    LString value ->
      (counter, emitStringLiteral value)
    LBool True ->
      (counter, "true")
    LBool False ->
      (counter, "false")
    LPage title body ->
      let (counterAfterTitle, titleText) = emitExpr counter title
          (counterAfterBody, bodyText) = emitExpr counterAfterTitle body
       in ( counterAfterBody
          , "{ $kind: \"page\", title: " <> titleText <> ", body: " <> bodyText <> " }"
          )
    LRedirect targetPath ->
      (counter, "{ $kind: \"redirect\", location: " <> emitStringLiteral targetPath <> ", status: 303 }")
    LViewEmpty ->
      (counter, "{ $kind: \"empty\" }")
    LViewText value ->
      let (nextCounter, valueText) = emitExpr counter value
       in (nextCounter, "{ $kind: \"text\", text: " <> valueText <> " }")
    LViewAppend left right ->
      let (counterAfterLeft, leftText) = emitExpr counter left
          (counterAfterRight, rightText) = emitExpr counterAfterLeft right
       in ( counterAfterRight
          , "{ $kind: \"append\", left: " <> leftText <> ", right: " <> rightText <> " }"
          )
    LViewElement tagName child ->
      let (nextCounter, childText) = emitExpr counter child
       in ( nextCounter
          , "{ $kind: \"element\", tag: " <> emitStringLiteral tagName <> ", child: " <> childText <> " }"
          )
    LViewStyled styleRef child ->
      let (nextCounter, childText) = emitExpr counter child
       in ( nextCounter
          , "{ $kind: \"styled\", styleRef: " <> emitStringLiteral styleRef <> ", child: " <> childText <> " }"
          )
    LViewLink routeContract href child ->
      let (nextCounter, childText) = emitExpr counter child
       in ( nextCounter
          , "{ $kind: \"link\", contract: " <> emitRouteContractObject routeContract <> ", href: " <> emitStringLiteral href <> ", child: " <> childText <> " }"
          )
    LViewForm routeContract method action child ->
      let (nextCounter, childText) = emitExpr counter child
       in ( nextCounter
          , "{ $kind: \"form\", contract: " <> emitRouteContractObject routeContract <> ", method: " <> emitStringLiteral method <> ", action: " <> emitStringLiteral action <> ", child: " <> childText <> " }"
          )
    LViewInput fieldName inputKind value ->
      let (nextCounter, valueText) = emitExpr counter value
       in ( nextCounter
          , "{ $kind: \"input\", fieldName: " <> emitStringLiteral fieldName <> ", inputKind: " <> emitStringLiteral inputKind <> ", value: " <> valueText <> " }"
          )
    LViewSubmit label ->
      let (nextCounter, labelText) = emitExpr counter label
       in (nextCounter, "{ $kind: \"submit\", label: " <> labelText <> " }")
    LCall fn args ->
      let (counterAfterFn, fnText) = emitExpr counter fn
          (counterAfterArgs, argTexts) = emitExprList counterAfterFn args
       in ( counterAfterArgs
          , fnText
              <> "("
              <> T.intercalate ", " argTexts
              <> ")"
          )
    LConstruct tag fields ->
      let (nextCounter, fieldTexts) = emitExprList counter fields
          objectFields =
            T.intercalate ", " $
              ("$tag: " <> emitStringLiteral tag)
                : [ emitFieldName index <> ": " <> fieldText
                  | (index, fieldText) <- zip [(0 :: Int) ..] fieldTexts
                  ]
       in (nextCounter, "{ " <> objectFields <> " }")
    LRecord fields ->
      let (nextCounter, fieldTexts) = emitRecordFields counter fields
       in (nextCounter, "{ " <> T.intercalate ", " fieldTexts <> " }")
    LFieldAccess subject fieldName ->
      let (nextCounter, subjectText) = emitExpr counter subject
       in (nextCounter, "(" <> subjectText <> ")." <> emitPropertyName fieldName)
    LMatch subject branches ->
      let (counterAfterSubject, subjectText) = emitExpr counter subject
          matchVar = "$match" <> T.pack (show counterAfterSubject)
          (counterAfterBranches, branchTexts) = emitMatchBranches (counterAfterSubject + 1) matchVar branches
          switchBody =
            T.unlines $
              fmap ("    " <>) branchTexts
                <> ["    default: throw new Error(\"Non-exhaustive match\");"]
       in ( counterAfterBranches
          , T.unlines
              [ "(() => {"
              , "  const " <> matchVar <> " = " <> subjectText <> ";"
              , "  switch (" <> matchVar <> ".$tag) {"
              , switchBody
              , "  }"
              , "})()"
              ]
          )

emitRouteContractObject :: LowerRouteContract -> Text
emitRouteContractObject routeContract =
  "{ routeName: "
    <> emitStringLiteral (lowerRouteContractName routeContract)
    <> ", routeId: "
    <> emitStringLiteral (lowerRouteContractIdentity routeContract)
    <> ", method: "
    <> emitStringLiteral (lowerRouteContractMethod routeContract)
    <> ", path: "
    <> emitStringLiteral (lowerRouteContractPath routeContract)
    <> ", pathDecl: "
    <> emitRoutePathDecl (lowerRouteContractPathDecl routeContract)
    <> ", requestType: "
    <> emitStringLiteral (lowerRouteContractRequestType routeContract)
    <> ", queryDecl: "
    <> emitRouteBoundaryDecl [] [] (lowerRouteContractQueryDecl routeContract)
    <> ", formDecl: "
    <> emitRouteBoundaryDecl [] [] (lowerRouteContractFormDecl routeContract)
    <> ", bodyDecl: "
    <> emitRouteBoundaryDecl [] [] (lowerRouteContractBodyDecl routeContract)
    <> ", responseType: "
    <> emitStringLiteral (lowerRouteContractResponseType routeContract)
    <> ", responseDecl: "
    <> emitRouteBoundaryDecl [] [] (Just (lowerRouteContractResponseDecl routeContract))
    <> ", responseKind: "
    <> emitStringLiteral (lowerRouteContractResponseKind routeContract)
    <> " }"

emitExprList :: Int -> [LowerExpr] -> (Int, [Text])
emitExprList counter exprs =
  foldl emitOne (counter, []) exprs
  where
    emitOne (nextCounter, rendered) expr =
      let (updatedCounter, renderedExpr) = emitExpr nextCounter expr
       in (updatedCounter, rendered <> [renderedExpr])

emitRecordFields :: Int -> [LowerRecordField] -> (Int, [Text])
emitRecordFields counter fields =
  foldl emitOne (counter, []) fields
  where
    emitOne (nextCounter, rendered) field =
      let (updatedCounter, fieldValueText) = emitExpr nextCounter (lowerRecordFieldValue field)
          renderedField =
            emitPropertyName (lowerRecordFieldName field)
              <> ": "
              <> fieldValueText
       in (updatedCounter, rendered <> [renderedField])

emitMatchBranches :: Int -> Text -> [LowerMatchBranch] -> (Int, [Text])
emitMatchBranches counter matchVar branches =
  foldl emitOne (counter, []) branches
  where
    emitOne (nextCounter, rendered) branch =
      let (updatedCounter, renderedBranch) = emitMatchBranch nextCounter matchVar branch
       in (updatedCounter, rendered <> [renderedBranch])

emitMatchBranch :: Int -> Text -> LowerMatchBranch -> (Int, Text)
emitMatchBranch counter matchVar branch =
  let bindingLines =
        [ "const "
            <> emitIdentifier binder
            <> " = "
            <> matchVar
            <> "."
            <> emitFieldName index
            <> ";"
        | (index, binder) <- zip [(0 :: Int) ..] (lowerMatchBranchBinders branch)
        ]
      (nextCounter, bodyText) = emitExpr counter (lowerMatchBranchBody branch)
      bodyLines =
        fmap ("      " <>) bindingLines
          <> ["      return " <> bodyText <> ";"]
   in ( nextCounter
      , T.unlines $
          [ "case " <> emitStringLiteral (lowerMatchBranchTag branch) <> ": {"
          ]
            <> bodyLines
            <> ["    }"]
      )

emitFieldName :: Int -> Text
emitFieldName index =
  "$" <> T.pack (show index)

emitPropertyName :: Text -> Text
emitPropertyName = emitIdentifier

emitIdentifier :: Text -> Text
emitIdentifier = id

emitStringLiteral :: Text -> Text
emitStringLiteral value =
  T.pack (show (T.unpack value))
