{-# LANGUAGE OverloadedStrings #-}

module Clasp.Emit.JavaScript
  ( emitModule
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Clasp.Lower
  ( LowerDecl (..)
  , LowerExpr (..)
  , LowerMatchBranch (..)
  , LowerModule (..)
  , LowerRecordField (..)
  , LowerRoute (..)
  )
import Clasp.Syntax
  ( ConstructorDecl (..)
  , ForeignDecl (..)
  , IntComparisonOp (..)
  , ModuleName (..)
  , RecordDecl (..)
  , RecordFieldDecl (..)
  , RouteMethod (..)
  , Type (..)
  , TypeDecl (..)
  )

emitModule :: LowerModule -> Text
emitModule modl =
  T.unlines $
    [ "// Generated by claspc"
    , "// Source module: " <> unModuleName (lowerModuleName modl)
    ]
      <> emitRuntimePrelude
      <> emitPrimitiveCodecHelpers
      <> concatMap emitTypeCodecHelpers (lowerModuleTypeDecls modl)
      <> concatMap emitRecordCodecHelpers (lowerModuleRecordDecls modl)
      <> emitForeignBindings (lowerModuleForeignDecls modl)
      <> snd (emitDecls 0 (lowerModuleDecls modl))
      <> emitRoutesExport (lowerModuleRoutes modl)

emitRuntimePrelude :: [Text]
emitRuntimePrelude =
  [ ""
  , "function $claspRuntime(name) {"
  , "  const runtime = globalThis.__claspRuntime;"
  , "  if (!runtime || !(name in runtime)) {"
  , "    throw new Error(`Missing Clasp runtime binding: ${name}`);"
  , "  }"
  , "  return runtime[name];"
  , "}"
  , ""
  , "function $claspExpectObject(value, path) {"
  , "  if (typeof value !== \"object\" || value === null || Array.isArray(value)) {"
  , "    throw new Error(`${path} expected an object`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspExpectInt(value, path) {"
  , "  if (!Number.isInteger(value)) {"
  , "    throw new Error(`${path} expected an Int`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspExpectStr(value, path) {"
  , "  if (typeof value !== \"string\") {"
  , "    throw new Error(`${path} expected a Str`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspExpectBool(value, path) {"
  , "  if (typeof value !== \"boolean\") {"
  , "    throw new Error(`${path} expected a Bool`);"
  , "  }"
  , "  return value;"
  , "}"
  , ""
  , "function $claspRequireField(objectValue, fieldName, path) {"
  , "  if (!Object.prototype.hasOwnProperty.call(objectValue, fieldName)) {"
  , "    throw new Error(`${path}.${fieldName} is missing`);"
  , "  }"
  , "  return objectValue[fieldName];"
  , "}"
  , ""
  ]

emitPrimitiveCodecHelpers :: [Text]
emitPrimitiveCodecHelpers =
  [ "function $decode_Int(jsonText) { return $claspExpectInt(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Int(value) { return JSON.stringify($claspExpectInt(value, \"value\")); }"
  , "function $decode_Str(jsonText) { return $claspExpectStr(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Str(value) { return JSON.stringify($claspExpectStr(value, \"value\")); }"
  , "function $decode_Bool(jsonText) { return $claspExpectBool(JSON.parse(jsonText), \"value\"); }"
  , "function $encode_Bool(value) { return JSON.stringify($claspExpectBool(value, \"value\")); }"
  , ""
  ]

emitTypeCodecHelpers :: TypeDecl -> [Text]
emitTypeCodecHelpers typeDecl
  | isJsonEnumTypeDecl typeDecl =
      [ "function " <> validateName <> "(value, path = \"value\") {"
      , "  const textValue = $claspExpectStr(value, path);"
      , "  switch (textValue) {"
      ]
        <> concatMap emitValidateCase constructors
        <> [ "    default: throw new Error(`${path} expected one of: " <> expectedValues <> "`);"
           , "  }"
           , "}"
           , "function " <> validateInternalName <> "(value, path = \"value\") {"
           , "  const tag = typeof value === \"object\" && value !== null ? value.$tag : null;"
           , "  switch (tag) {"
           ]
        <> concatMap emitValidateInternalCase constructors
        <> [ "    default: throw new Error(`${path} expected a " <> typeDeclName typeDecl <> " value`);"
           , "  }"
           , "}"
           , "function " <> serializeName <> "(value, path = \"value\") {"
           , "  const tag = typeof value === \"object\" && value !== null ? value.$tag : null;"
           , "  switch (tag) {"
           ]
        <> concatMap emitSerializeCase constructors
        <> [ "    default: throw new Error(`${path} expected a " <> typeDeclName typeDecl <> " value`);"
           , "  }"
           , "}"
           , "function " <> decodeName <> "(jsonText) { return " <> validateName <> "(JSON.parse(jsonText), \"value\"); }"
           , "function " <> encodeName <> "(value) { return JSON.stringify(" <> serializeName <> "(value, \"value\")); }"
           , ""
           ]
  | otherwise =
      []
  where
    constructors = typeDeclConstructors typeDecl
    expectedValues = T.intercalate ", " (fmap constructorWireValue constructors)
    validateName = "$validate_" <> typeDeclName typeDecl
    validateInternalName = "$validateInternal_" <> typeDeclName typeDecl
    serializeName = "$serialize_" <> typeDeclName typeDecl
    decodeName = "$decode_" <> typeDeclName typeDecl
    encodeName = "$encode_" <> typeDeclName typeDecl

    emitValidateCase constructorDecl =
      [ "    case "
          <> emitStringLiteral (constructorWireValue constructorDecl)
          <> ": return "
          <> emitIdentifier (constructorDeclName constructorDecl)
          <> ";"
      ]

    emitValidateInternalCase constructorDecl =
      [ "    case "
          <> emitStringLiteral (constructorDeclName constructorDecl)
          <> ": return value;"
      ]

    emitSerializeCase constructorDecl =
      [ "    case "
          <> emitStringLiteral (constructorDeclName constructorDecl)
          <> ": return "
          <> emitStringLiteral (constructorWireValue constructorDecl)
          <> ";"
      ]

emitRecordCodecHelpers :: RecordDecl -> [Text]
emitRecordCodecHelpers recordDecl =
  [ "function " <> validateName <> "(value, path = \"value\") {"
  , "  const objectValue = $claspExpectObject(value, path);"
  ]
    <> concatMap emitValidateField (recordDeclFields recordDecl)
    <> [ "  return { " <> T.intercalate ", " (fmap (\fieldDecl -> recordFieldDeclName fieldDecl <> ": " <> recordFieldDeclName fieldDecl) (recordDeclFields recordDecl)) <> " };"
       , "}"
       , "function " <> validateInternalName <> "(value, path = \"value\") {"
       , "  const objectValue = $claspExpectObject(value, path);"
       ]
    <> concatMap emitValidateInternalField (recordDeclFields recordDecl)
    <> [ "  return { " <> T.intercalate ", " (fmap (\fieldDecl -> recordFieldDeclName fieldDecl <> ": " <> recordFieldDeclName fieldDecl) (recordDeclFields recordDecl)) <> " };"
       , "}"
       , "function " <> serializeName <> "(value) {"
       ]
    <> concatMap emitSerializeField (recordDeclFields recordDecl)
    <> [ "  return { " <> T.intercalate ", " (fmap (\fieldDecl -> recordFieldDeclName fieldDecl <> ": " <> recordFieldDeclName fieldDecl) (recordDeclFields recordDecl)) <> " };"
       , "}"
       , "function " <> decodeName <> "(jsonText) { return " <> validateName <> "(JSON.parse(jsonText), \"value\"); }"
       , "function " <> encodeName <> "(value) { return JSON.stringify(" <> serializeName <> "(" <> validateInternalName <> "(value, \"value\"))); }"
       , ""
       ]
  where
    validateName = "$validate_" <> recordDeclName recordDecl
    validateInternalName = "$validateInternal_" <> recordDeclName recordDecl
    serializeName = "$serialize_" <> recordDeclName recordDecl
    decodeName = "$decode_" <> recordDeclName recordDecl
    encodeName = "$encode_" <> recordDeclName recordDecl

    emitValidateField fieldDecl =
      let fieldName = recordFieldDeclName fieldDecl
          fieldPath = "path + " <> emitStringLiteral ("." <> fieldName)
       in [ "  const " <> fieldName <> "Value = $claspRequireField(objectValue, " <> emitStringLiteral fieldName <> ", path);"
          , "  const " <> fieldName <> " = " <> emitValidator (recordFieldDeclType fieldDecl) (fieldName <> "Value") fieldPath <> ";"
          ]

    emitValidateInternalField fieldDecl =
      let fieldName = recordFieldDeclName fieldDecl
          fieldPath = "path + " <> emitStringLiteral ("." <> fieldName)
       in [ "  const " <> fieldName <> "Value = $claspRequireField(objectValue, " <> emitStringLiteral fieldName <> ", path);"
          , "  const " <> fieldName <> " = " <> emitInternalValidator (recordFieldDeclType fieldDecl) (fieldName <> "Value") fieldPath <> ";"
          ]

    emitSerializeField fieldDecl =
      let fieldName = recordFieldDeclName fieldDecl
       in [ "  const " <> fieldName <> " = " <> emitSerializer (recordFieldDeclType fieldDecl) ("value." <> fieldName) <> ";" ]

emitForeignBindings :: [ForeignDecl] -> [Text]
emitForeignBindings foreignDecls =
  fmap emitForeignBinding foreignDecls <> [""]
  where
    emitForeignBinding foreignDecl =
      let params = foreignParams (foreignDeclType foreignDecl)
          runtimeCall =
            "$claspRuntime("
              <> emitStringLiteral (foreignDeclRuntimeName foreignDecl)
              <> ")("
              <> T.intercalate ", " params
              <> ")"
       in "function "
            <> emitIdentifier (foreignDeclName foreignDecl)
            <> "("
            <> T.intercalate ", " params
            <> ") { return "
            <> runtimeCall
            <> "; }"

foreignParams :: Type -> [Text]
foreignParams typ =
  case typ of
    TFunction args _ ->
      fmap (("$" <>) . T.pack . show) [(0 :: Int) .. length args - 1]
    _ ->
      []

emitRoutesExport :: [LowerRoute] -> [Text]
emitRoutesExport routes =
  [ "export const __claspRoutes = ["
  ]
    <> concatMap emitRoute routes
    <> [ "];" ]
  where
    emitRoute route =
      [ "  {"
      , "    name: " <> emitStringLiteral (lowerRouteName route) <> ","
      , "    method: " <> emitStringLiteral (emitRouteMethod (lowerRouteMethod route)) <> ","
      , "    path: " <> emitStringLiteral (lowerRoutePath route) <> ","
      , "    requestType: " <> emitStringLiteral (lowerRouteRequestTypeName route) <> ","
      , "    responseType: " <> emitStringLiteral (lowerRouteResponseTypeName route) <> ","
      , "    handler: " <> emitIdentifier (lowerRouteHandlerName route) <> ","
      , "    decodeRequest: $decode_" <> lowerRouteRequestTypeName route <> ","
      , "    encodeResponse: $encode_" <> lowerRouteResponseTypeName route
      , "  },"
      ]

emitRouteMethod :: RouteMethod -> Text
emitRouteMethod routeMethod =
  case routeMethod of
    RouteGet ->
      "GET"
    RoutePost ->
      "POST"

emitValidator :: Type -> Text -> Text -> Text
emitValidator typ valueRef pathRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", " <> pathRef <> ")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", " <> pathRef <> ")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", " <> pathRef <> ")"
    TList _ ->
      "(() => { throw new Error(\"Lists are not JSON serializable yet\"); })()"
    TNamed name ->
      "$validate_" <> name <> "(" <> valueRef <> ", " <> pathRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitInternalValidator :: Type -> Text -> Text -> Text
emitInternalValidator typ valueRef pathRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", " <> pathRef <> ")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", " <> pathRef <> ")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", " <> pathRef <> ")"
    TList _ ->
      "(() => { throw new Error(\"Lists are not JSON serializable yet\"); })()"
    TNamed name ->
      "$validateInternal_" <> name <> "(" <> valueRef <> ", " <> pathRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

emitSerializer :: Type -> Text -> Text
emitSerializer typ valueRef =
  case typ of
    TInt ->
      "$claspExpectInt(" <> valueRef <> ", \"value\")"
    TStr ->
      "$claspExpectStr(" <> valueRef <> ", \"value\")"
    TBool ->
      "$claspExpectBool(" <> valueRef <> ", \"value\")"
    TList _ ->
      "(() => { throw new Error(\"Lists are not JSON serializable yet\"); })()"
    TNamed name ->
      "$serialize_" <> name <> "(" <> valueRef <> ")"
    TFunction _ _ ->
      "(() => { throw new Error(\"Functions are not JSON serializable\"); })()"

isJsonEnumTypeDecl :: TypeDecl -> Bool
isJsonEnumTypeDecl typeDecl =
  all (null . constructorDeclFields) (typeDeclConstructors typeDecl)

constructorWireValue :: ConstructorDecl -> Text
constructorWireValue constructorDecl =
  T.toLower (constructorDeclName constructorDecl)

emitDecls :: Int -> [LowerDecl] -> (Int, [Text])
emitDecls counter decls =
  foldl emitOne (counter, []) decls
  where
    emitOne (nextCounter, rendered) decl =
      let (updatedCounter, renderedDecl) = emitDecl nextCounter decl
       in (updatedCounter, rendered <> [renderedDecl])

emitDecl :: Int -> LowerDecl -> (Int, Text)
emitDecl counter decl =
  case decl of
    LValueDecl name expr ->
      let (nextCounter, bodyText) = emitExpr counter expr
       in ( nextCounter
          , "export const "
              <> emitIdentifier name
              <> " = "
              <> bodyText
              <> ";"
          )
    LFunctionDecl name params body ->
      let (nextCounter, bodyText) = emitExpr counter body
       in ( nextCounter
          , "export function "
              <> emitIdentifier name
              <> "("
              <> T.intercalate ", " (fmap emitIdentifier params)
              <> ") { return "
              <> bodyText
              <> "; }"
          )

emitExpr :: Int -> LowerExpr -> (Int, Text)
emitExpr counter expr =
  case expr of
    LVar name ->
      (counter, emitIdentifier name)
    LInt value ->
      (counter, T.pack (show value))
    LString value ->
      (counter, emitStringLiteral value)
    LBool True ->
      (counter, "true")
    LBool False ->
      (counter, "false")
    LEqual left right ->
      let (counterAfterLeft, leftText) = emitExpr counter left
          (counterAfterRight, rightText) = emitExpr counterAfterLeft right
       in (counterAfterRight, "(" <> leftText <> " === " <> rightText <> ")")
    LIntCompare op left right ->
      let (counterAfterLeft, leftText) = emitExpr counter left
          (counterAfterRight, rightText) = emitExpr counterAfterLeft right
       in (counterAfterRight, "(" <> leftText <> " " <> emitIntComparisonOp op <> " " <> rightText <> ")")
    LCall fn args ->
      let (counterAfterFn, fnText) = emitExpr counter fn
          (counterAfterArgs, argTexts) = emitExprList counterAfterFn args
       in ( counterAfterArgs
          , fnText
              <> "("
              <> T.intercalate ", " argTexts
              <> ")"
          )
    LConstruct tag fields ->
      let (nextCounter, fieldTexts) = emitExprList counter fields
          objectFields =
            T.intercalate ", " $
              ("$tag: " <> emitStringLiteral tag)
                : [ emitFieldName index <> ": " <> fieldText
                  | (index, fieldText) <- zip [(0 :: Int) ..] fieldTexts
                  ]
       in (nextCounter, "{ " <> objectFields <> " }")
    LRecord fields ->
      let (nextCounter, fieldTexts) = emitRecordFields counter fields
       in (nextCounter, "{ " <> T.intercalate ", " fieldTexts <> " }")
    LFieldAccess subject fieldName ->
      let (nextCounter, subjectText) = emitExpr counter subject
       in (nextCounter, "(" <> subjectText <> ")." <> emitPropertyName fieldName)
    LMatch subject branches ->
      let (counterAfterSubject, subjectText) = emitExpr counter subject
          matchVar = "$match" <> T.pack (show counterAfterSubject)
          (counterAfterBranches, branchTexts) = emitMatchBranches (counterAfterSubject + 1) matchVar branches
          switchBody =
            T.unlines $
              fmap ("    " <>) branchTexts
                <> ["    default: throw new Error(\"Non-exhaustive match\");"]
       in ( counterAfterBranches
          , T.unlines
              [ "(() => {"
              , "  const " <> matchVar <> " = " <> subjectText <> ";"
              , "  switch (" <> matchVar <> ".$tag) {"
              , switchBody
              , "  }"
              , "})()"
              ]
          )

emitExprList :: Int -> [LowerExpr] -> (Int, [Text])
emitExprList counter exprs =
  foldl emitOne (counter, []) exprs
  where
    emitOne (nextCounter, rendered) expr =
      let (updatedCounter, renderedExpr) = emitExpr nextCounter expr
       in (updatedCounter, rendered <> [renderedExpr])

emitRecordFields :: Int -> [LowerRecordField] -> (Int, [Text])
emitRecordFields counter fields =
  foldl emitOne (counter, []) fields
  where
    emitOne (nextCounter, rendered) field =
      let (updatedCounter, fieldValueText) = emitExpr nextCounter (lowerRecordFieldValue field)
          renderedField =
            emitPropertyName (lowerRecordFieldName field)
              <> ": "
              <> fieldValueText
       in (updatedCounter, rendered <> [renderedField])

emitMatchBranches :: Int -> Text -> [LowerMatchBranch] -> (Int, [Text])
emitMatchBranches counter matchVar branches =
  foldl emitOne (counter, []) branches
  where
    emitOne (nextCounter, rendered) branch =
      let (updatedCounter, renderedBranch) = emitMatchBranch nextCounter matchVar branch
       in (updatedCounter, rendered <> [renderedBranch])

emitMatchBranch :: Int -> Text -> LowerMatchBranch -> (Int, Text)
emitMatchBranch counter matchVar branch =
  let bindingLines =
        [ "const "
            <> emitIdentifier binder
            <> " = "
            <> matchVar
            <> "."
            <> emitFieldName index
            <> ";"
        | (index, binder) <- zip [(0 :: Int) ..] (lowerMatchBranchBinders branch)
        ]
      (nextCounter, bodyText) = emitExpr counter (lowerMatchBranchBody branch)
      bodyLines =
        fmap ("      " <>) bindingLines
          <> ["      return " <> bodyText <> ";"]
   in ( nextCounter
      , T.unlines $
          [ "case " <> emitStringLiteral (lowerMatchBranchTag branch) <> ": {"
          ]
            <> bodyLines
            <> ["    }"]
      )

emitFieldName :: Int -> Text
emitFieldName index =
  "$" <> T.pack (show index)

emitPropertyName :: Text -> Text
emitPropertyName = emitIdentifier

emitIdentifier :: Text -> Text
emitIdentifier = id

emitStringLiteral :: Text -> Text
emitStringLiteral value =
  T.pack (show (T.unpack value))

emitIntComparisonOp :: IntComparisonOp -> Text
emitIntComparisonOp op =
  case op of
    IntLessThan ->
      "<"
    IntLessThanOrEqual ->
      "<="
    IntGreaterThan ->
      ">"
    IntGreaterThanOrEqual ->
      ">="
