// Generated by compiler-selfhost
function $claspSnapshotValue(value) {
  if (typeof globalThis.structuredClone === "function") {
    return globalThis.structuredClone(value);
  }
  return value === undefined ? undefined : JSON.parse(JSON.stringify(value));
}

function $claspExpectObject(value, path = "value") {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${path} expected an object`);
  }
  return value;
}

function $claspExpectArray(value, path = "value") {
  if (!Array.isArray(value)) {
    throw new Error(`${path} expected an array`);
  }
  return value;
}

function $claspExpectString(value, path = "value") {
  if (typeof value !== "string") {
    throw new Error(`${path} expected a string`);
  }
  return value;
}

function $claspExpectInt(value, path = "value") {
  if (!Number.isInteger(value)) {
    throw new Error(`${path} expected an integer`);
  }
  return value;
}

function $claspExpectBool(value, path = "value") {
  if (typeof value !== "boolean") {
    throw new Error(`${path} expected a boolean`);
  }
  return value;
}

function $claspPromptMessage(role, content) {
  return Object.freeze({
    $kind: "prompt",
    messages: Object.freeze([Object.freeze({
      role: $claspExpectString(role, "prompt.role"),
      content: $claspExpectString(content, "prompt.content")
    })])
  });
}

function $claspExpectPrompt(value, path = "value") {
  const objectValue = $claspExpectObject(value, path);
  if (objectValue.$kind !== "prompt") {
    throw new Error(`${path} expected a Prompt value`);
  }
  const messages = $claspExpectArray(objectValue.messages, `${path}.messages`).map((message, index) => {
    const messagePath = `${path}.messages[${index}]`;
    const messageObject = $claspExpectObject(message, messagePath);
    return Object.freeze({
      role: $claspExpectString(messageObject.role, `${messagePath}.role`),
      content: $claspExpectString(messageObject.content, `${messagePath}.content`)
    });
  });
  return Object.freeze({ $kind: "prompt", messages: Object.freeze(messages) });
}

function systemPrompt(content) { return $claspPromptMessage("system", content); }
function assistantPrompt(content) { return $claspPromptMessage("assistant", content); }
function userPrompt(content) { return $claspPromptMessage("user", content); }

function appendPrompt(left, right) {
  const leftPrompt = $claspExpectPrompt(left, "left");
  const rightPrompt = $claspExpectPrompt(right, "right");
  return Object.freeze({
    $kind: "prompt",
    messages: Object.freeze([...leftPrompt.messages, ...rightPrompt.messages].map((message) => Object.freeze({ role: message.role, content: message.content })))
  });
}

function promptText(value) {
  const prompt = $claspExpectPrompt(value, "value");
  return prompt.messages.map((message) => `${message.role}: ${message.content}`).join("\n\n");
}

function $claspCreateTraceCollector(seed = []) {
  const entries = Array.isArray(seed) ? seed.map((entry) => $claspSnapshotValue(entry)) : [];
  return Object.freeze({
    kind: "clasp-trace-collector",
    version: 1,
    record(entry) {
      const snapshot = $claspSnapshotValue(entry);
      entries.push(snapshot);
      return snapshot;
    },
    entries() {
      return $claspSnapshotValue(entries);
    },
    clear() {
      entries.length = 0;
      return this.entries();
    }
  });
}

function $claspMaybeRecordTrace(options = null, kind, name, action) {
  const collector = options && typeof options === "object" && options.collector && typeof options.collector.record === "function"
    ? options.collector
    : null;
  if (collector) {
    collector.record(Object.freeze({ kind, name, action, status: "ok" }));
  }
}
export const hello = "Hello from Clasp";
export function id(value) { return value; }
export const main = id(hello);
const __claspExports = Object.freeze({ hello: hello, id: id, main: main });

export const __claspSchemas = Object.freeze({  });

export const __claspTraceCollector = Object.freeze({
  version: 1,
  create(seed = []) { return $claspCreateTraceCollector(seed); }
});

export const __claspModule = Object.freeze({
  name: "Main",
  version: 1
});

export const __claspBindings = Object.freeze({
  kind: "clasp-generated-bindings",
  version: 1,
  module: __claspModule,
  schemas: __claspSchemas,
  traces: __claspTraceCollector
});
