#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_root="$(mktemp -d)"

cleanup() {
  rm -rf "$test_root"
}

trap cleanup EXIT

build_root="$project_root/runtime"
claspc_bin="$build_root/target/debug/claspc"
frontend_output="$test_root/hello.mjs"
backend_project_dir="$test_root/backend-project"
backend_project_path="$backend_project_dir/Main.clasp"
backend_binary="$test_root/backend-app"
cli_project_dir="$test_root/cli-project"
cli_project_path="$cli_project_dir/Main.clasp"
cli_binary="$test_root/cli-app"
cli_output_path="$test_root/argv.txt"
bootstrap_rejection="$test_root/bootstrap-rejection.json"

mkdir -p "$backend_project_dir"
cat >"$backend_project_path" <<'EOF'
module Main

record LeadRequest = { company : Str }
record LeadSummary = { summary : Str }

summarizeLead : LeadRequest -> LeadSummary
summarizeLead lead = LeadSummary { summary = lead.company }

showInbox : LeadRequest -> Page
showInbox lead = page lead.company (styled "lead_shell" (element "main" (append (element "p" (text "ready")) (append (link "/lead/redirect" (text "Open redirect")) (form "POST" "/lead/redirect" (append (input "company" "text" lead.company) (submit "Save")))))))

redirectToInbox : LeadRequest -> Redirect
redirectToInbox lead = redirect "/lead/inbox"

route summarizeLeadRoute = POST "/lead/summary" LeadRequest -> LeadSummary summarizeLead
route inboxRoute = GET "/lead/inbox" LeadRequest -> Page showInbox
route redirectRoute = POST "/lead/redirect" LeadRequest -> Redirect redirectToInbox

main : Str
main = "ok"
EOF

mkdir -p "$cli_project_dir"
cat >"$cli_project_path" <<EOF
module Main

argsText : Str
argsText = textJoin "," argv

main : Str
main = match writeFile "$(printf '%s' "$cli_output_path")" argsText {
  Ok written -> argsText,
  Err message -> message
}
EOF

(
  cd "$project_root"
  cargo build --quiet --manifest-path runtime/Cargo.toml --bin claspc
)

[[ -x "$claspc_bin" ]]

"$claspc_bin" --json check "$project_root/examples/hello.clasp" | grep -F '"status":"ok"' >/dev/null
"$claspc_bin" compile "$project_root/examples/hello.clasp" -o "$frontend_output"
grep -F '// Generated by compiler-selfhost' "$frontend_output" >/dev/null

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$backend_project_path" -o "$backend_binary"
[[ -x "$backend_binary" ]]
"$backend_binary" | grep -F 'ok' >/dev/null
"$backend_binary" route POST /lead/summary '{"company":"Acme"}' | grep -F '{"summary":"Acme"}' >/dev/null
page_json="$("$backend_binary" route GET /lead/inbox '{"company":"Inbox"}')"
printf '%s\n' "$page_json" | grep -F '"kind":"page"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"title":"Inbox"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"body":{"kind":"styled","styleRef":"lead_shell"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"tag":"main"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"link","href":"/lead/redirect"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"form","method":"POST","action":"/lead/redirect"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"input","fieldName":"company","inputKind":"text","value":"Inbox"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"submit","label":"Save"' >/dev/null
"$backend_binary" route POST /lead/redirect '{"company":"Inbox"}' | grep -F '{"kind":"redirect","location":"/lead/inbox"}' >/dev/null

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$cli_project_path" -o "$cli_binary"
[[ -x "$cli_binary" ]]
"$cli_binary" alpha beta | grep -F 'alpha,beta' >/dev/null
grep -F 'alpha,beta' "$cli_output_path" >/dev/null

if "$claspc_bin" --json --compiler=bootstrap check "$project_root/examples/hello.clasp" >"$bootstrap_rejection"; then
  :
else
  :
fi
grep -F '"status":"error"' "$bootstrap_rejection" >/dev/null
grep -F 'deprecated compiler selection is gone' "$bootstrap_rejection" >/dev/null
