#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_root="$(mktemp -d)"
server_pid=""

cleanup() {
  if [[ -n "$server_pid" ]]; then
    kill "$server_pid" >/dev/null 2>&1 || true
    wait "$server_pid" >/dev/null 2>&1 || true
  fi
  rm -rf "$test_root"
}

trap cleanup EXIT

stop_server() {
  if [[ -n "$server_pid" ]]; then
    kill "$server_pid" >/dev/null 2>&1 || true
    wait "$server_pid" >/dev/null 2>&1 || true
    server_pid=""
  fi
}

build_root="$project_root/runtime"
claspc_bin="$build_root/target/debug/claspc"
frontend_output="$test_root/hello.mjs"
backend_project_dir="$test_root/backend-project"
backend_project_path="$backend_project_dir/Main.clasp"
backend_binary="$test_root/backend-app"
cli_project_dir="$test_root/cli-project"
cli_project_path="$cli_project_dir/Main.clasp"
cli_binary="$test_root/cli-app"
cli_output_path="$test_root/argv.txt"
imported_cli_project_dir="$test_root/imported-cli-project"
imported_cli_project_path="$imported_cli_project_dir/Main.clasp"
imported_cli_binary="$test_root/imported-cli-app"
imported_cli_output_path="$test_root/imported-output.txt"
imported_cli_serial_image="$test_root/imported-cli-serial.native.image.json"
imported_cli_parallel_image="$test_root/imported-cli-parallel.native.image.json"
swarm_kernel_binary="$test_root/swarm-kernel"
swarm_state_root="$test_root/swarm/state"
swarm_event_log="$swarm_state_root/events.jsonl"
support_console_binary="$test_root/support-console-app"
release_gate_binary="$test_root/release-gate-app"
lead_app_binary="$test_root/lead-app"
bootstrap_rejection="$test_root/bootstrap-rejection.json"
server_log="$test_root/native-server.log"
server_headers="$test_root/server-headers.txt"
server_body="$test_root/server-body.txt"
support_server_log="$test_root/support-server.log"
release_server_log="$test_root/release-server.log"
lead_server_log="$test_root/lead-server.log"

mkdir -p "$backend_project_dir"
cat >"$backend_project_path" <<'EOF'
module Main

record LeadRequest = { company : Str }
record LeadSummary = { summary : Str }

summarizeLead : LeadRequest -> LeadSummary
summarizeLead lead = LeadSummary { summary = lead.company }

showInbox : LeadRequest -> Page
showInbox lead = page lead.company (styled "lead_shell" (element "main" (append (element "p" (text "ready")) (append (link "/lead/redirect" (text "Open redirect")) (form "POST" "/lead/redirect" (append (input "company" "text" lead.company) (submit "Save")))))))

redirectToInbox : LeadRequest -> Redirect
redirectToInbox lead = redirect "/lead/inbox"

route summarizeLeadRoute = POST "/lead/summary" LeadRequest -> LeadSummary summarizeLead
route inboxRoute = GET "/lead/inbox" LeadRequest -> Page showInbox
route redirectRoute = POST "/lead/redirect" LeadRequest -> Redirect redirectToInbox

main : Str
main = "ok"
EOF

mkdir -p "$cli_project_dir"
cat >"$cli_project_path" <<EOF
module Main

argsText : Str
argsText = textJoin "," argv

main : Str
main = match writeFile "$(printf '%s' "$cli_output_path")" argsText {
  Ok written -> argsText,
  Err message -> message
}
EOF

mkdir -p "$imported_cli_project_dir/Shared"
cat >"$imported_cli_project_path" <<EOF
module Main
import Shared.User
import Shared.Render

main : Str
main = match writeFile "$(printf '%s' "$imported_cli_output_path")" (renderUser primaryUser) {
  Ok written -> renderUser primaryUser,
  Err message -> message
}
EOF

cat >"$imported_cli_project_dir/Shared/User.clasp" <<'EOF'
module Shared.User

record User = { name : Str, role : Str }

primaryUser : User
primaryUser = User { name = "Ada", role = "planner" }
EOF

cat >"$imported_cli_project_dir/Shared/Render.clasp" <<'EOF'
module Shared.Render
import Shared.User

renderUser : User -> Str
renderUser user = textJoin ":" [user.name, user.role]
EOF

(
  cd "$project_root"
  cargo build --quiet --manifest-path runtime/Cargo.toml --bin claspc
)

[[ -x "$claspc_bin" ]]

"$claspc_bin" --json check "$project_root/examples/hello.clasp" | grep -F '"status":"ok"' >/dev/null
"$claspc_bin" compile "$project_root/examples/hello.clasp" -o "$frontend_output"
grep -F '// Generated by compiler-selfhost' "$frontend_output" >/dev/null
release_gate_check="$("$claspc_bin" --json check "$project_root/examples/release-gate/Main.clasp")"
printf '%s\n' "$release_gate_check" | grep -F '"status":"ok"' >/dev/null
printf '%s\n' "$release_gate_check" | grep -F 'opsSession : AuthSession' >/dev/null
printf '%s\n' "$release_gate_check" | grep -F 'opsTenantId : AuthSession -> Str' >/dev/null
printf '%s\n' "$release_gate_check" | grep -F 'dashboard : Empty -> Page' >/dev/null
lead_app_check="$("$claspc_bin" --json check "$project_root/examples/lead-app/Main.clasp")"
printf '%s\n' "$lead_app_check" | grep -F '"status":"ok"' >/dev/null
printf '%s\n' "$lead_app_check" | grep -F 'outreachPrompt : LeadRecord -> LeadPlaybook -> Prompt' >/dev/null
printf '%s\n' "$lead_app_check" | grep -F 'outreachPromptText : LeadRecord -> LeadPlaybook -> Str' >/dev/null
printf '%s\n' "$lead_app_check" | grep -F 'draftLeadOutreach : LeadRecord -> LeadPlaybook -> LeadOutreachDraft' >/dev/null
support_console_check="$("$claspc_bin" --json check "$project_root/examples/support-console/Main.clasp")"
printf '%s\n' "$support_console_check" | grep -F '"status":"ok"' >/dev/null
printf '%s\n' "$support_console_check" | grep -F 'supportSession : AuthSession' >/dev/null
printf '%s\n' "$support_console_check" | grep -F 'currentCustomer : SupportCustomer' >/dev/null
printf '%s\n' "$support_console_check" | grep -F 'dashboard : Empty -> Page' >/dev/null

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$backend_project_path" -o "$backend_binary"
[[ -x "$backend_binary" ]]
"$backend_binary" | grep -F 'ok' >/dev/null
"$backend_binary" route POST /lead/summary '{"company":"Acme"}' | grep -F '{"summary":"Acme"}' >/dev/null
page_json="$("$backend_binary" route GET /lead/inbox '{"company":"Inbox"}')"
printf '%s\n' "$page_json" | grep -F '"kind":"page"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"title":"Inbox"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"body":{"kind":"styled","styleRef":"lead_shell"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"tag":"main"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"link","href":"/lead/redirect"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"form","method":"POST","action":"/lead/redirect"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"input","fieldName":"company","inputKind":"text","value":"Inbox"' >/dev/null
printf '%s\n' "$page_json" | grep -F '"kind":"submit","label":"Save"' >/dev/null
"$backend_binary" route POST /lead/redirect '{"company":"Inbox"}' | grep -F '{"kind":"redirect","location":"/lead/inbox"}' >/dev/null

server_port="$(python - <<'PY'
import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
)"
server_addr="127.0.0.1:$server_port"
"$backend_binary" serve "$server_addr" >"$server_log" 2>&1 &
server_pid=$!
for _ in $(seq 1 50); do
  if curl -sS -o /dev/null -X GET -H 'content-type: application/json' --data '{"company":"Inbox"}' "http://$server_addr/lead/inbox" 2>/dev/null; then
    break
  fi
  sleep 0.1
done
server_page_json="$(curl -sS -X GET -H 'content-type: application/json' --data '{"company":"Inbox"}' "http://$server_addr/lead/inbox")"
printf '%s\n' "$server_page_json" | grep -F '"kind":"page"' >/dev/null
printf '%s\n' "$server_page_json" | grep -F '"title":"Inbox"' >/dev/null
curl -sS -D "$server_headers" -o "$server_body" -X POST -H 'content-type: application/json' --data '{"company":"Inbox"}' "http://$server_addr/lead/redirect" >/dev/null
grep -F 'HTTP/1.1 303 See Other' "$server_headers" >/dev/null
grep -Fi 'Location: /lead/inbox' "$server_headers" >/dev/null
grep -F '{"kind":"redirect","location":"/lead/inbox"}' "$server_body" >/dev/null
stop_server

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$cli_project_path" -o "$cli_binary"
[[ -x "$cli_binary" ]]
"$cli_binary" alpha beta | grep -F 'alpha,beta' >/dev/null
grep -F 'alpha,beta' "$cli_output_path" >/dev/null

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$imported_cli_project_path" -o "$imported_cli_binary"
[[ -x "$imported_cli_binary" ]]
"$imported_cli_binary" | grep -F 'Ada:planner' >/dev/null
grep -F 'Ada:planner' "$imported_cli_output_path" >/dev/null
CLASP_NATIVE_BUNDLE_JOBS=1 CLASP_NATIVE_IMAGE_SECTION_JOBS=1 "$claspc_bin" native-image "$imported_cli_project_path" -o "$imported_cli_serial_image"
CLASP_NATIVE_BUNDLE_JOBS=4 CLASP_NATIVE_IMAGE_SECTION_JOBS=4 "$claspc_bin" native-image "$imported_cli_project_path" -o "$imported_cli_parallel_image"
cmp -s "$imported_cli_serial_image" "$imported_cli_parallel_image"

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$project_root/examples/swarm-kernel/Main.clasp" -o "$swarm_kernel_binary"
[[ -x "$swarm_kernel_binary" ]]
swarm_result_path="$(CLASP_SWARM_ACTOR=planner "$swarm_kernel_binary" "$swarm_state_root")"
[[ "$swarm_result_path" == "$swarm_event_log" ]]
[[ -f "$swarm_event_log" ]]
grep -F '"kind":"task_created"' "$swarm_event_log" >/dev/null
grep -F '"taskId":"bootstrap"' "$swarm_event_log" >/dev/null
grep -F '"actor":"planner"' "$swarm_event_log" >/dev/null
grep -F '"detail":"Initialize swarm kernel state."' "$swarm_event_log" >/dev/null
grep -E '"atMs":[0-9]+' "$swarm_event_log" >/dev/null

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$project_root/examples/support-console/Main.clasp" -o "$support_console_binary"
[[ -x "$support_console_binary" ]]
"$support_console_binary" route GET /support/customer '{}' | grep -F '"contactEmail":"ops@northwind.example"' >/dev/null
"$support_console_binary" route GET /support/customer/page '{}' | grep -F '"title":"Customer export"' >/dev/null

support_server_port="$(python - <<'PY'
import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
)"
support_server_addr="127.0.0.1:$support_server_port"
"$support_console_binary" serve "$support_server_addr" >"$support_server_log" 2>&1 &
server_pid=$!
for _ in $(seq 1 50); do
  if curl -sS -o /dev/null "http://$support_server_addr/support" 2>/dev/null; then
    break
  fi
  sleep 0.1
done
curl -sS "http://$support_server_addr/support" | grep -F '"title":"Support console"' >/dev/null
curl -sS "http://$support_server_addr/support/customer/page" | grep -F '"title":"Customer export"' >/dev/null
curl -sS -X POST -H 'content-type: application/x-www-form-urlencoded' --data 'customerId=cust-42&summary=Renewal+is+blocked+on+legal+review.' "http://$support_server_addr/support/preview" | grep -F 'Thanks for the update. Renewal is blocked on legal review. We will send the next renewal step today.' >/dev/null
stop_server

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$project_root/examples/release-gate/Main.clasp" -o "$release_gate_binary"
[[ -x "$release_gate_binary" ]]
"$release_gate_binary" route GET /release/audit '{}' | grep -F '"releaseId":"rel-204"' >/dev/null
"$release_gate_binary" route GET /release/audit '{}' | grep -F '"status":{"$tag":"Pending"}' >/dev/null

release_server_port="$(python - <<'PY'
import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
)"
release_server_addr="127.0.0.1:$release_server_port"
"$release_gate_binary" serve "$release_server_addr" >"$release_server_log" 2>&1 &
server_pid=$!
for _ in $(seq 1 50); do
  if curl -sS -o /dev/null "http://$release_server_addr/release-gate" 2>/dev/null; then
    break
  fi
  sleep 0.1
done
curl -sS "http://$release_server_addr/release-gate" | grep -F '"title":"Release gate"' >/dev/null
curl -sS -X POST -H 'content-type: application/x-www-form-urlencoded' --data 'releaseId=rel-204&summary=Ship+the+support+automation+pipeline.' "http://$release_server_addr/release/review" | grep -F 'Approved after typed policy review.' >/dev/null
curl -sS -D "$server_headers" -o "$server_body" -X POST "http://$release_server_addr/release/accept" >/dev/null
grep -F 'HTTP/1.1 303 See Other' "$server_headers" >/dev/null
grep -Fi 'Location: /release/ack' "$server_headers" >/dev/null
stop_server

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$project_root/examples/lead-app/Main.clasp" -o "$lead_app_binary"
[[ -x "$lead_app_binary" ]]
lead_create_json="$("$lead_app_binary" route POST /api/leads '{"company":"SynthSpeak API","contact":"Ava Stone","budget":25000,"segment":"Growth"}')"
printf '%s\n' "$lead_create_json" | grep -F '"leadId":"lead-3"' >/dev/null
printf '%s\n' "$lead_create_json" | grep -F '"priority":{"$tag":"Medium"}' >/dev/null
printf '%s\n' "$lead_create_json" | grep -F '"segment":{"$tag":"Growth"}' >/dev/null

lead_server_port="$(python - <<'PY'
import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
)"
lead_server_addr="127.0.0.1:$lead_server_port"
"$lead_app_binary" serve "$lead_server_addr" >"$lead_server_log" 2>&1 &
server_pid=$!
for _ in $(seq 1 50); do
  if curl -sS -o /dev/null "http://$lead_server_addr/api/inbox" 2>/dev/null; then
    break
  fi
  sleep 0.1
done
curl -sS "http://$lead_server_addr/api/inbox" | grep -F '"headline":"Priority inbox"' >/dev/null
created_lead_json="$(curl -sS -X POST -H 'content-type: application/json' --data '{"company":"SynthSpeak API","contact":"Ava Stone","budget":25000,"segment":"Growth"}' "http://$lead_server_addr/api/leads")"
printf '%s\n' "$created_lead_json" | grep -F '"leadId":"lead-3"' >/dev/null
curl -sS "http://$lead_server_addr/api/lead/primary" | grep -F '"company":"SynthSpeak API"' >/dev/null
reviewed_lead_json="$(curl -sS -X POST -H 'content-type: application/json' --data '{"leadId":"lead-3","note":"Schedule technical discovery"}' "http://$lead_server_addr/api/review")"
printf '%s\n' "$reviewed_lead_json" | grep -F '"reviewNote":"Schedule technical discovery"' >/dev/null
curl -sS -o "$server_body" -w '%{http_code}' -X POST -H 'content-type: application/json' --data '{"company":"Bad Budget Co","contact":"Casey","budget":"oops","segment":"Growth"}' "http://$lead_server_addr/api/leads" | grep -F '400' >/dev/null
grep -F 'budget must be an integer' "$server_body" >/dev/null
curl -sS -o "$server_body" -w '%{http_code}' -X POST -H 'content-type: application/json' --data '{"leadId":"lead-404","note":"Missing"}' "http://$lead_server_addr/api/review" | grep -F '502' >/dev/null
grep -F 'Unknown lead: lead-404' "$server_body" >/dev/null
stop_server

if "$claspc_bin" --json --compiler=bootstrap check "$project_root/examples/hello.clasp" >"$bootstrap_rejection"; then
  :
else
  :
fi
grep -F '"status":"error"' "$bootstrap_rejection" >/dev/null
grep -F 'deprecated compiler selection is gone' "$bootstrap_rejection" >/dev/null
