#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require_pattern() {
  local path="$1"
  local pattern="$2"

  if ! grep -F -- "$pattern" "$project_root/$path" >/dev/null; then
    printf 'missing swarm-ready gate pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
}

reject_pattern() {
  local path="$1"
  local pattern="$2"

  if grep -F -- "$pattern" "$project_root/$path" >/dev/null; then
    printf 'unexpected swarm-ready gate pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
}

bash -n "$project_root/scripts/test-native-claspc.sh" "$project_root/scripts/test-native-claspc-smoke.sh" "$project_root/scripts/test-int-builtins.sh" "$project_root/scripts/test-dict-builtins.sh" "$project_root/scripts/test-native-runtime-smoke.sh" "$project_root/scripts/test-verify-all-smoke.sh" "$project_root/scripts/test-agent-command-template.sh" "$project_root/scripts/test-goal-manager-agent-command-template.sh" "$project_root/scripts/test-goal-manager-default-planner-command.sh" "$project_root/scripts/test-swarm-ready-benchmark.sh" "$project_root/scripts/test-swarm-memory.sh" "$project_root/scripts/test-swarm-context-pack.sh" "$project_root/benchmarks/test-benchmark-prep-cache.sh"
bash -n "$project_root/scripts/test-goal-manager-planner-report-decode.sh"
bash -n "$project_root/examples/swarm-kernel/scripts/verify.sh"
node "$project_root/scripts/check-promoted-native-image-exports.mjs" >/dev/null

require_pattern "examples/feedback-loop/Main.clasp" 'codexModel = readEnvText "CLASP_LOOP_CODEX_MODEL_JSON" (readEnvText "CLASP_LOOP_AGENT_MODEL_JSON" "gpt-5.5")'
require_pattern "examples/feedback-loop/Main.clasp" 'codexReasoning = readEnvText "CLASP_LOOP_CODEX_REASONING_JSON" (readEnvText "CLASP_LOOP_AGENT_REASONING_JSON" "xhigh")'
require_pattern "examples/feedback-loop/Main.clasp" 'agentCommandTemplate = readEnvCommandTextList "CLASP_LOOP_AGENT_COMMAND_JSON" emptyTexts'
require_pattern "examples/feedback-loop/Main.clasp" 'renderAgentCommand role schemaPath reportPath promptPath'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'codexModel = readEnvText "CLASP_LOOP_CODEX_MODEL_JSON" (readEnvText "CLASP_LOOP_AGENT_MODEL_JSON" "gpt-5.5")'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'codexReasoning = readEnvText "CLASP_LOOP_CODEX_REASONING_JSON" (readEnvText "CLASP_LOOP_AGENT_REASONING_JSON" "xhigh")'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'plannerAgentCommandTemplate = readEnvTextList "CLASP_MANAGER_PLANNER_AGENT_COMMAND_JSON" agentCommandTemplate'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'plannerAgentCommandArgs'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'codexCommandDefault schemaPath reportPath prompt'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'plannerContextSectionFor wave'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'Planner context pack:'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'taskContextPack (plannerHandleForWave wave)'
reject_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'planner-stdin'
require_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '"{prompt}"'
require_pattern "scripts/test-agent-command-template.sh" 'agent-command-template-ok'
require_pattern "scripts/test-agent-command-template.sh" 'native-provider-neutral-agent-template-ok'
require_pattern "scripts/test-agent-command-template.sh" 'native-clasp-local-agent-template-ok'
require_pattern "scripts/test-agent-command-template.sh" 'CLASP_AGENT_COMMAND_TEMPLATE_NATIVE'
require_pattern "scripts/test-agent-command-template.sh" 'examples/swarm-native/FeedbackLoop.clasp'
require_pattern "scripts/test-agent-command-template.sh" 'examples/swarm-native/LocalAgent.clasp'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" '{prompt_path}'
require_pattern "scripts/verify-all.sh" 'CLASP_AGENT_COMMAND_TEMPLATE_FEEDBACK=0 CLASP_AGENT_COMMAND_TEMPLATE_NATIVE=1 bash scripts/test-agent-command-template.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-goal-manager-agent-command-template.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-goal-manager-default-planner-command.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-dict-builtins.sh'
require_pattern "scripts/verify-all.sh" 'bash benchmarks/test-benchmark-prep-cache.sh'
require_pattern "scripts/verify-fast.sh" 'bash benchmarks/test-benchmark-prep-cache.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-swarm-memory.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-swarm-memory.sh'
require_pattern "scripts/verify-affected.mjs" 'bash scripts/test-swarm-memory.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-swarm-ready-benchmark.sh'
require_pattern "scripts/verify-affected.mjs" 'bash scripts/test-swarm-ready-benchmark.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-swarm-context-pack.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-swarm-context-pack.sh'
require_pattern "scripts/verify-affected.mjs" 'bash scripts/test-swarm-context-pack.sh'
require_pattern "examples/swarm-native/Swarm.clasp" 'memoryPut : SwarmRoot -> Str -> Str -> Str -> Str -> Str -> Result SwarmMemory'
require_pattern "examples/swarm-native/Swarm.clasp" 'memorySearch : SwarmRoot -> Str -> Str -> Str -> Int -> Result [SwarmMemorySearchResult]'
require_pattern "examples/swarm-native/Swarm.clasp" 'record SwarmArtifactContent ='
require_pattern "examples/swarm-native/Swarm.clasp" 'artifactRead : SwarmRoot -> Int -> Int -> Result SwarmArtifactContent'
require_pattern "examples/swarm-native/Swarm.clasp" 'record SwarmContextPack ='
require_pattern "examples/swarm-native/Swarm.clasp" 'taskContextPack : TaskHandle -> Str -> Int -> Result SwarmContextPack'
require_pattern "examples/swarm-native/Swarm.clasp" 'allowedProcesses : [Str]'
require_pattern "examples/swarm-native/Swarm.clasp" 'allowedWorkspaceRoots : [Str]'
require_pattern "examples/swarm-native/Swarm.clasp" 'networkAccess : Str'
require_pattern "examples/swarm-native/Swarm.clasp" 'policySetWithProcessAccess'
require_pattern "examples/swarm-native/Swarm.clasp" 'policySetWithAccess'
require_pattern "examples/swarm-native/Swarm.clasp" 'policySetWithCapabilities'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'renderContextPackPrompt : SwarmContextPack -> Str'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'taskContextPromptSection : TaskHandle -> Str -> Int -> Str'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'builderContextSection attempt'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'verifierContextSection attempt'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'writeFeedbackAndMemory'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'CLASP_LOOP_BUILDER_TIMEOUT_MS_JSON'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'CLASP_LOOP_VERIFIER_TIMEOUT_MS_JSON'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'CLASP_LOOP_BUILDER_MEMORY_MB_JSON'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'CLASP_LOOP_VERIFIER_MEMORY_MB_JSON'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'toolRunWithOptionalLimits (builderHandle attempt) (builderCommand attempt) builderTimeoutMs builderMemoryLimitMb'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'verifierRunWithOptionalLimits (verifierHandle attempt) "autonomous-confidence" (verifierCommand attempt) verifierTimeoutMs verifierMemoryLimitMb'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'finishToolRun (builderHandle attempt) runValue'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'finishToolRun (verifierHandle attempt) runValue'
require_pattern "scripts/test-swarm-native-feedback-loop.sh" 'CLASP_LOOP_BUILDER_TIMEOUT_MS_JSON'
require_pattern "scripts/test-swarm-native-feedback-loop.sh" 'CLASP_LOOP_BUILDER_MEMORY_MB_JSON'
require_pattern "scripts/test-swarm-native-feedback-loop.sh" 'timedOut=true'
require_pattern "examples/swarm-native/MemoryHarness.clasp" 'mailboxValues = map memoryValue mailboxValue.memory'
require_pattern "examples/swarm-native/MemoryHarness.clasp" 'searchValues = map searchMemoryValue searchValues'
require_pattern "examples/swarm-native/ContextPackHarness.clasp" 'taskContextPack repairTask "focused compiler verifier" 10'
require_pattern "examples/swarm-native/ContextPackHarness.clasp" 'traceClassifications = map verificationTraceFailedVerifierClassification pack.runTrace'
require_pattern "examples/swarm-native/ContextPackHarness.clasp" 'artifactRead root pick.artifactId 16'
require_pattern "examples/swarm-native/ContextPackHarness.clasp" 'artifactExcerptTexts = map artifactExcerptText pack.artifactExcerpts'
require_pattern "scripts/test-swarm-context-pack.sh" 'artifact read should report truncation'
require_pattern "scripts/test-swarm-context-pack.sh" 'context-verifier-warning'
require_pattern "examples/swarm-native/ManagedLoop.clasp" 'managedLoopRecordFailureMemory'
require_pattern "examples/swarm-native/ManagedLoop.clasp" 'taskContextPack (managedLoopTaskHandle spec) "managed loop failure verifier context"'
require_pattern "examples/swarm-native/ManagedLoop.clasp" 'runToolStepWithOptionalLimits'
require_pattern "examples/swarm-native/ManagedLoop.clasp" 'executeVerificationPlanWithOptionalLimits'
require_pattern "examples/swarm-native/Swarm.clasp" 'contextMemoryValues : [Str]'
require_pattern "scripts/test-swarm-native-managed-loop.sh" 'managed context memory values'
require_pattern "scripts/test-swarm-native-managed-loop.sh" 'budget context memory values'
require_pattern "scripts/test-agent-command-template.sh" 'second builder prompt should include native context pack evidence'
require_pattern "scripts/test-agent-command-template.sh" 'verifier-feedback'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'promptHasBuilderContextPack'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'promptHasVerifierContextPack'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'promptHasTaskFileContent'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'local-agent-error:missing builder context pack'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'local-agent-error:missing verifier context pack'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'local-agent-error:missing task file content'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'clasp-local-agent-context-pack'
require_pattern "examples/swarm-native/LocalAgent.clasp" 'clasp-local-agent-task-file-prompt'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'taskFileContentSection'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'Task file content:'
require_pattern "examples/swarm-native/FeedbackLoop.clasp" 'artifactExcerptPromptSection "artifact excerpts:" pack.artifactExcerpts'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'plannerArtifactExcerptSection "artifact excerpts:" pack.artifactExcerpts'
require_pattern "scripts/test-agent-command-template.sh" 'local builder should record context-pack coverage'
require_pattern "scripts/test-agent-command-template.sh" 'local verifier should report native context-pack consumption evidence'
require_pattern "scripts/test-agent-command-template.sh" 'native generic template should receive inlined task file content'
require_pattern "scripts/test-agent-command-template.sh" 'local verifier should report task-file prompt evidence'
require_pattern "runtime/swarm.rs" 'CREATE TABLE IF NOT EXISTS swarm_memory'
require_pattern "runtime/swarm.rs" 'fn memory_search_json'
require_pattern "runtime/swarm.rs" 'allowed_processes_json'
require_pattern "runtime/swarm.rs" 'allowed_workspace_roots_json'
require_pattern "runtime/swarm.rs" 'network_access'
require_pattern "runtime/swarm.rs" 'process_permission_denied'
require_pattern "runtime/swarm.rs" 'workspace_permission_denied'
require_pattern "runtime/swarm.rs" '--allow-process'
require_pattern "runtime/swarm.rs" '--allow-workspace'
require_pattern "runtime/swarm.rs" '--deny-network'
require_pattern "scripts/test-native-claspc.sh" 'process `sh` is not allowed by task policy'
require_pattern "scripts/test-native-claspc.sh" 'is outside allowed workspace roots'
require_pattern "scripts/test-native-claspc.sh" '"networkAccess":"denied"'
require_pattern "scripts/verify-affected.mjs" 'node --check benchmarks/run-benchmark.mjs'
require_pattern "scripts/verify-affected.mjs" 'bash benchmarks/test-benchmark-prep-cache.sh'
require_pattern "benchmarks/test-benchmark-prep-cache.sh" 'test-benchmark-prep-cache: ok'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'goal-manager-agent-command-template-ok'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'ensure-goal-manager-binary.sh'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'CLASP_GOAL_MANAGER_COMPILE_MEMORY_MB'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'examples/swarm-native/LocalPlanner.clasp'
require_pattern "examples/swarm-native/LocalPlanner.clasp" 'clasp-local-planner'
require_pattern "examples/swarm-native/LocalPlanner.clasp" 'promptHasPlannerContextPack'
require_pattern "examples/swarm-native/LocalPlanner.clasp" 'planner-error:missing native context pack'
require_pattern "examples/swarm-native/LocalPlanner.clasp" 'clasp-local-planner-context-pack'
require_pattern "examples/swarm-native/LocalPlanner.clasp" 'native-context-pack'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'Codex fallback backend should not be invoked'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'planner prompt missing native context pack'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'Clasp planner task should consume native context pack evidence'
require_pattern "scripts/test-goal-manager-fixture-manager.mjs" 'fixture manager completed'
require_pattern "scripts/test-goal-manager-fixture-manager.mjs" 'Planner context pack:'
require_pattern "scripts/test-goal-manager-fixture-manager.mjs" 'task: planner-1 status=ready ready=true attempts=0'
require_pattern "scripts/test-goal-manager-default-planner-command.sh" 'goal-manager-default-planner-command-ok'
require_pattern "scripts/test-goal-manager-default-planner-command.sh" 'default planner command should pass the prompt as an argument'
require_pattern "scripts/test-goal-manager-default-planner-command.sh" 'default planner source missing native context pack pattern'
require_pattern "scripts/test-goal-manager-default-planner-command.sh" 'ensure-goal-manager-binary.sh'
require_pattern "scripts/test-goal-manager-default-planner-command.sh" 'CLASP_GOAL_MANAGER_COMPILE_MEMORY_MB'
require_pattern "examples/feedback-loop/Main.clasp" 'watchModeEnabled'
require_pattern "examples/feedback-loop/Main.clasp" '"builder-running"'
require_pattern "examples/feedback-loop/Main.clasp" '"verifier-running"'
require_pattern "examples/feedback-loop/Main.clasp" 'Verification tier: focused.'
require_pattern "examples/feedback-loop/Main.clasp" 'Do not run `bash scripts/verify-all.sh` for this focused branch.'
require_pattern "examples/feedback-loop/Main.clasp" 'CLASP_LOOP_FOCUSED_VERIFIER_TIMEOUT_MS_JSON'
require_pattern "examples/feedback-loop/Main.clasp" 'ensureStepReportWithTimeout'
require_pattern "examples/feedback-loop/Main.clasp" 'diff -ruN '
require_pattern "examples/feedback-loop/Main.clasp" 'verifierShellCommand'
require_pattern "examples/feedback-loop/Main.clasp" 'CLASP_LOOP_BASELINE_WORKSPACE_JSON'
require_pattern "examples/feedback-loop/Main.clasp" 'focusedVerifySelectionPath'
require_pattern "examples/feedback-loop/Main.clasp" 'Focused verification command source: '
require_pattern "examples/feedback-loop/Main.clasp" 'import FocusedSelection'
require_pattern "examples/feedback-loop/FocusedSelection.clasp" 'bash scripts/verify-fast.sh'
require_pattern "examples/feedback-loop/FocusedSelection.clasp" 'bash scripts/test-feedback-loop-routing.sh loop-routing'
require_pattern "scripts/test-feedback-loop-routing.sh" 'FocusedSelectionProbe.clasp'
reject_pattern "examples/feedback-loop/Main.clasp" '"file: workspace.txt"'
reject_pattern "examples/feedback-loop/Main.clasp" '"--exclude=workspace.txt "'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-feedback-loop-resume.sh'
require_pattern "scripts/test-feedback-loop-resume.sh" 'CLASP_TEST_SHARED_XDG_CACHE_HOME'
require_pattern "scripts/test-feedback-loop-resume.sh" 'CLASP_TEST_ISOLATED_XDG_CACHE'
require_pattern "examples/feedback-loop/Process.clasp" 'awaitWatchedProcessTimeoutJson'
require_pattern "examples/feedback-loop/MonitoredWorkflowDemo.clasp" 'workflow-status.json'
require_pattern "examples/feedback-loop/MonitoredWorkflowDemo.clasp" 'failure-detected'
require_pattern "examples/feedback-loop/MonitoredWorkflowDemo.clasp" '"failed-handled"'
require_pattern "examples/feedback-loop/CodexLoopDemo.clasp" 'ordinary-clasp-codex-loop'
require_pattern "examples/feedback-loop/CodexLoopDemo.clasp" 'codex-loop-status.json'
require_pattern "examples/feedback-loop/CodexLoopDemo.clasp" 'codexExecCommand'
require_pattern "scripts/test-codex-loop-program.sh" 'codex-loop-program-ok'
require_pattern "examples/swarm-native/GoalManager.clasp" 'heartbeatTaskLease'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_PLANNER_POLICY_JSON'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_TASK_WORKSPACE_ROOT_JSON'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_TASK_PROMOTION_HEARTBEAT_JSON'
require_pattern "examples/swarm-native/GoalManagerServiceMain.clasp" 'CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON='
require_pattern "examples/swarm-native/GoalManager.clasp" 'planner external resource blocked'
require_pattern "examples/swarm-native/GoalManager.clasp" 'external-resource-blocker'
require_pattern "examples/swarm-native/GoalManager.clasp" 'Do not inspect files, run shell commands, invoke tools, or gather extra repository context from the planner.'
require_pattern "examples/swarm-native/GoalManager.clasp" 'Return the final planner-report JSON immediately; do not stream interim plans or empty task lists.'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'Do not inspect files, run shell commands, invoke tools, or gather extra repository context from the planner.'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'Return the final planner-report JSON immediately; do not stream interim plans or empty task lists.'
require_pattern "examples/swarm-native/GoalManager.clasp" 'already exists'
require_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '--exclude=libclasp_runtime.a'
require_pattern "examples/swarm-native/GoalManagerPrelude.clasp" 'repairPromotedNativeWorkspaceArtifacts'
require_pattern "examples/swarm-native/GoalManagerBootstrapSetup.clasp" 'workspace-artifact-error'
require_pattern "examples/swarm-native/GoalManagerTaskWorkspaceRuntime.clasp" 'task workspace artifact repair failed'
reject_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '--exclude=src/stage1*.native.image.json'
reject_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '--exclude=src/embedded*.native.image.json'
reject_pattern "examples/swarm-native/GoalManager.clasp" '--exclude=src/stage1*.native.image.json'
reject_pattern "examples/swarm-native/GoalManager.clasp" '--exclude=src/embedded*.native.image.json'
require_pattern "examples/swarm-native/GoalManager.clasp" 'plannerReportFromRaw : Str -> Result PlannerReport'
require_pattern "examples/swarm-native/GoalManager.clasp" 'planner report missing required fields'
require_pattern "examples/swarm-native/GoalManagerReportIO.clasp" 'plannerReportFromRaw : Str -> Result PlannerReport'
require_pattern "examples/swarm-native/PlannerReportDecodeHarness.clasp" 'malformed-empty-tasks'
require_pattern "examples/swarm-native/PlannerReportDecodeHarness.clasp" '{\"tasks\":[]}'
require_pattern "examples/swarm-native/PlannerReportDecodeHarness.clasp" 'legacy-task'
require_pattern "scripts/test-goal-manager-planner-report-decode.sh" 'current-empty-tasks=ok:0:current empty'
reject_pattern "examples/swarm-native/GoalManager.clasp" 'plannerReportFromRaw : Str -> PlannerReport'
reject_pattern "examples/swarm-native/GoalManagerReportIO.clasp" 'plannerReportFromRaw : Str -> PlannerReport'
reject_pattern "examples/swarm-native/GoalManager.scratch.clasp" 'plannerReportFromRaw : Str -> PlannerReport'
require_pattern "runtime/claspc.rs" 'embedded_final_status_output'
require_pattern "runtime/clasp_runtime.rs" 'finalStatusPath'
require_pattern "scripts/test-goal-manager-fast.sh" 'runtime failed to execute native compiler export'
require_pattern "scripts/test-goal-manager-fast.sh" 'CLASP_TEST_FAKE_PLANNER_USAGE_LIMIT_FAILS'
require_pattern "scripts/test-goal-manager-fast.sh" 'CLASP_TEST_FAKE_PLANNER_MALFORMED_REPORT'
require_pattern "scripts/test-goal-manager-fast.sh" 'CLASP_TEST_EXPECT_PLANNER_PROMPT_ARG'
require_pattern "scripts/test-goal-manager-fast.sh" 'malformed planner report should not crash the native export boundary'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'childLoopAwaitTimeoutMs = readEnvInt "CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON" 10000'
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON='
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitor.clasp" 'heartbeatTaskLease'
require_pattern "examples/swarm-native/GoalManagerTaskExecutionHelpers.clasp" 'recoverExpiredTaskFailureRecording'
require_pattern "examples/swarm-native/GoalManagerWatch.clasp" 'awaitWatchedProcessTimeout'
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitor.clasp" 'awaitChildLoopOutcome'
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitor.clasp" 'monitoredLoopAwait'
require_pattern "examples/swarm-native/GoalManagerWatch.clasp" 'if message == "timeout" then'
require_pattern "examples/swarm-native/GoalManagerWatch.clasp" 'reconcileWatchedProcess heartbeatPath'
require_pattern "scripts/test-goal-manager-fast.sh" "CLASP_MANAGER_TASK_WORKSPACE_CACHE_MAX_MB_JSON='16'"
require_pattern "examples/swarm-native/GoalManagerBenchmarkCommand.clasp" 'benchmarkDefaultPassSignal'
require_pattern "examples/swarm-native/GoalManagerBenchmarkCommand.clasp" 'benchmark command passed without signal'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" 'record MonitoredLoopOutcome'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"completed-pass"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"completed-fail"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"missing-heartbeat"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"malformed-unresolved-heartbeat"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"retry-exhausted"'
require_pattern "examples/swarm-native/GoalManagerTaskStatusRuntime.clasp" 'childLoopLaunchOutcome'
require_pattern "examples/swarm-native/MonitoredLoopHarness.clasp" 'monitoredLoopSpawn'
require_pattern "examples/swarm-native/MonitoredLoopHarness.clasp" 'monitoredLoopLaunchOrResume'
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitorHarness.clasp" 'retryRecoveryWaitingReasonForTask'
require_pattern "examples/swarm-native/GoalManagerChildLoopControlHarness.clasp" 'objectiveCreate controlRoot'
require_pattern "examples/swarm-native/GoalManagerChildLoopControlHarness.clasp" 'awaitWatchedProcessTimeoutRaw'
require_pattern "scripts/test-monitored-loop.sh" 'retry-exhausted=retry-exhausted'
require_pattern "scripts/test-monitored-loop.sh" 'watch-pass=completed-pass'
require_pattern "scripts/test-goal-manager-child-loop-monitor.sh" 'lease-await=timeout'
require_pattern "scripts/test-goal-manager-child-loop-monitor.sh" 'lease-heartbeat-seen=true'
require_pattern "scripts/test-goal-manager-child-loop-monitor.sh" 'goal-manager-child-loop-monitor-ok'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-monitored-loop.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-monitored-workflow.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-codex-loop-program.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-goal-manager-child-loop-monitor.sh'
require_pattern "scripts/run-managed-job.sh" 'exit-status'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_TOKEN'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_STOP_REQUEST'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_MEMORY_MB'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_MIN_AVAILABLE_MEMORY_MB'
require_pattern "scripts/run-managed-job.sh" 'stop-request-path'
require_pattern "scripts/run-managed-job.sh" 'session_rss_kb'
require_pattern "scripts/run-managed-job.sh" 'host_available_memory_mb'
require_pattern "scripts/run-managed-job.sh" 'memory-exceeded'
require_pattern "scripts/run-managed-job.sh" 'systemd-run'
require_pattern "scripts/run-managed-job.sh" 'MemoryMax'
require_pattern "scripts/run-managed-job.sh" 'MemoryHigh'
require_pattern "scripts/run-managed-job.sh" 'memory-enforcer'
require_pattern "scripts/run-managed-job.sh" 'ulimit -c 0'
require_pattern "scripts/run-managed-job.sh" 'host-available-memory-reserve'
require_pattern "runtime/clasp_runtime.rs" 'processGroupId'
require_pattern "runtime/clasp_runtime.rs" 'CLASP_RT_WATCH_TOKEN'
require_pattern "runtime/clasp_runtime.rs" 'terminate_watched_process_tree'
require_pattern "runtime/clasp_runtime.rs" 'cancel_watched_process_json_stops_nested_process_group'
require_pattern "scripts/clasp-swarm-common.sh" 'clasp_swarm_require_managed_agent_runtime'
require_pattern "scripts/clasp-swarm-common.sh" 'CLASP_ALLOW_UNMANAGED_AGENT_RUNTIME'
require_pattern "scripts/clasp-codex-loop.sh" 'clasp_swarm_require_managed_agent_runtime'
require_pattern "scripts/clasp-autopilot.sh" 'clasp_swarm_require_managed_agent_runtime'
require_pattern "scripts/clasp-builder.sh" 'clasp_swarm_require_managed_agent_runtime'
require_pattern "scripts/clasp-verifier.sh" 'clasp_swarm_require_managed_agent_runtime'
require_pattern "scripts/test-codex-loop.sh" 'direct codex loop should refuse unmanaged agent work'
require_pattern "scripts/verify-all.sh" 'run-managed-job.sh'
require_pattern "scripts/verify-all.sh" 'CLASP_VERIFY_MANAGED_MEMORY_MB'
require_pattern "scripts/verify-all.sh" 'CLASP_VERIFY_MAX_PARALLEL_JOBS'
require_pattern "scripts/verify-all.sh" 'CLASP_NATIVE_JOBS_MAX="${CLASP_NATIVE_JOBS_MAX:-1}"'
require_pattern "scripts/verify-all.sh" 'CLASP_NATIVE_BUNDLE_JOBS="${CLASP_NATIVE_BUNDLE_JOBS:-1}"'
require_pattern "scripts/verify-all.sh" 'CLASP_NATIVE_IMAGE_SECTION_JOBS_MAX="${CLASP_NATIVE_IMAGE_SECTION_JOBS_MAX:-1}"'
require_pattern "scripts/verify-all.sh" 'CLASP_NATIVE_IMAGE_MODULE_DECL_FRESH_PROCESS="${CLASP_NATIVE_IMAGE_MODULE_DECL_FRESH_PROCESS:-1}"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_GOAL_MANAGER_COMPILE_MANAGED'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_GOAL_MANAGER_COMPILE_MEMORY_MB'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_GOAL_MANAGER_COMPILE_MIN_AVAILABLE_MEMORY_MB'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'run_goal_manager_compile_managed()'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'run-managed-job.sh" --jobs-root "$cache_root/compile-jobs"'
require_pattern "scripts/stop-managed-job.sh" 'stop-requested'
require_pattern "scripts/stop-managed-job.sh" '--force-signal'
require_pattern "scripts/stop-managed-job.sh" 'marked_session_pids'
require_pattern "scripts/stop-managed-job.sh" 'marked_job_pids'
require_pattern "scripts/stop-managed-job.sh" 'signal_validated_session_pids'
require_pattern "scripts/stop-managed-job.sh" 'refusing to stop unmarked session members'
require_pattern "scripts/test-managed-job.sh" 'complete-smoke'
require_pattern "scripts/test-managed-job.sh" 'instant-complete-smoke'
require_pattern "scripts/test-managed-job.sh" 'inherited-memory-limit-smoke'
require_pattern "scripts/test-managed-job.sh" 'marked-orphan-cleanup'
require_pattern "scripts/test-managed-job.sh" 'stop-root-exited-session'
require_pattern "scripts/test-managed-job.sh" 'forged-unmarked-session'
require_pattern "scripts/test-managed-job.sh" 'stop-unmarked-session-child'
require_pattern "scripts/test-managed-job.sh" 'memory-watch-smoke'
require_pattern "scripts/test-managed-job.sh" 'host-reserve-smoke'
require_pattern "scripts/test-managed-job.sh" 'memory-env-no-inherit'
require_pattern "scripts/test-managed-job.sh" 'systemd-scope|session-rss-watch'
require_pattern "scripts/test-managed-job.sh" 'core-limit-smoke'
require_pattern "scripts/clasp-codex-loop-start.sh" 'run-managed-job.sh'
require_pattern "scripts/clasp-codex-loop-start.sh" 'CLASP_CODEX_LOOP_MEMORY_MB'
require_pattern "scripts/clasp-codex-loop-start.sh" 'CLASP_CODEX_LOOP_MIN_AVAILABLE_MEMORY_MB'
require_pattern "scripts/clasp-codex-loop-stop.sh" 'stop-managed-job.sh'
require_pattern "scripts/clasp-codex-loop-stop.sh" 'refusing to signal without managed-job metadata'
require_pattern "scripts/clasp-swarm-start.sh" 'run-managed-job.sh'
require_pattern "scripts/clasp-swarm-start.sh" 'required_available_memory_mb'
require_pattern "scripts/clasp-swarm-start.sh" 'projected_running_lanes'
require_pattern "scripts/clasp-swarm-start.sh" '--min-available-memory-mb'
require_pattern "scripts/clasp-swarm-start.sh" 'CLASP_SWARM_NATIVE_JOBS_MAX'
require_pattern "scripts/clasp-swarm-start.sh" 'CLASP_NATIVE_JOBS_MAX="$native_jobs_max"'
require_pattern "scripts/clasp-swarm-start.sh" 'CLASP_SWARM_NATIVE_BUNDLE_JOBS'
require_pattern "scripts/clasp-swarm-start.sh" 'CLASP_NATIVE_BUNDLE_JOBS="$native_bundle_jobs"'
require_pattern "scripts/clasp-swarm-start.sh" 'CLASP_NATIVE_IMAGE_SECTION_JOBS_MAX="$native_image_section_jobs_max"'
require_pattern "scripts/clasp-swarm-stop.sh" 'stop-managed-job.sh'
require_pattern "scripts/clasp-swarm-stop.sh" 'refusing to signal without managed-job metadata'
require_pattern "scripts/clasp-autopilot-start.sh" 'run-managed-job.sh'
require_pattern "scripts/clasp-autopilot-start.sh" 'CLASP_AUTOPILOT_MEMORY_MB'
require_pattern "scripts/clasp-autopilot-start.sh" 'CLASP_AUTOPILOT_MIN_AVAILABLE_MEMORY_MB'
require_pattern "scripts/clasp-autopilot-stop.sh" 'stop-managed-job.sh'
require_pattern "scripts/clasp-autopilot-stop.sh" 'refusing to signal without managed-job metadata'
reject_pattern "scripts/clasp-codex-loop-stop.sh" 'kill -TERM -- "-\$pid"'
reject_pattern "scripts/clasp-codex-loop-stop.sh" 'kill -KILL -- "-\$pid"'
reject_pattern "scripts/clasp-swarm-stop.sh" 'kill_descendants'
reject_pattern "scripts/clasp-swarm-stop.sh" 'kill -9'
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASPC_BIN='
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASP_CLASPC='
require_pattern "examples/swarm-native/GoalManager.clasp" 'recoverExpiredTaskFailureRecording'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'childFocusedVerifyCommands'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" '    ""'
reject_pattern "examples/swarm-native/GoalManagerConfig.clasp" '    "bash scripts/test-goal-manager-fast.sh\nbash scripts/test-native-runtime.sh\nbash scripts/test-task-manifest.sh"'
reject_pattern "examples/swarm-native/GoalManager.clasp" '    "bash scripts/test-goal-manager-fast.sh\nbash scripts/test-native-runtime.sh\nbash scripts/test-task-manifest.sh"'

require_pattern "scripts/test-selfhost.sh" 'generate-promoted-module-summary-cache.mjs" --check'
require_pattern "scripts/test-selfhost.sh" 'CLASP_TEST_SELFHOST_SHARED_CACHE_HOME'
require_pattern "scripts/test-selfhost.sh" 'CLASP_TEST_ISOLATED_XDG_CACHE'
require_pattern "scripts/test-selfhost.sh" 'check-promoted-native-image-exports.mjs'
require_pattern "scripts/test-selfhost.sh" 'contextSourceText'
require_pattern "scripts/test-selfhost.sh" 'surfaceIndex'
require_pattern "scripts/test-selfhost.sh" 'clasp-dependency-graph-v1'
require_pattern "scripts/test-selfhost.sh" 'dependencyGraph missing Main -> Shared.Lead import edge'
require_pattern "scripts/test-selfhost.sh" 'mockLeadSummaryModel'
require_pattern "scripts/test-selfhost.sh" 'module-summary (promoted )?hit module=Compiler\.Ast'
require_pattern "scripts/test-selfhost.sh" 'module-summary (promoted )?hit module=Compiler\.Emit\.JavaScript'
require_pattern "scripts/test-selfhost.sh" 'module-summary (promoted )?hit module=Main'
require_pattern "scripts/verify-fast.sh" 'bash src/scripts/verify.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-selfhost.sh'
require_pattern "runtime/claspc.rs" 'stage1.compiler.module-summary-cache-v2.json'
require_pattern "runtime/claspc.rs" 'read_promoted_module_summary'
require_pattern "runtime/claspc.rs" 'promoted_module_summary_cache_text'
require_pattern "runtime/claspc.rs" 'Persist inside the worker so an outer timeout still preserves'
require_pattern "runtime/claspc.rs" 'decl-module-context-v2'
require_pattern "runtime/claspc.rs" 'augment_context_dependency_graph_output'
require_pattern "runtime/claspc.rs" 'clasp-dependency-graph-v1'
require_pattern "runtime/claspc.rs" 'decl-module summary-plan skipped; all chunk modules cached'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_BUILD_PLAN_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_DECL_MODULE_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_SOURCE_EXPORT_CACHE'
require_pattern "runtime/claspc.rs" 'source-export promoted output-path hit'
require_pattern "runtime/claspc.rs" 'read_cached_source_export(image_path, NATIVE_IMAGE_MONOLITHIC_EXPORT'
reject_pattern "scripts/resolve-claspc.sh" 'stage1.compiler.module-summary-cache-v2.json" -nt "$binary_path"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'goal_manager_relaxed_build_plan_cache="${CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE:-1}"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_PROJECT_ROOT="$project_root"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'validate_stale_goal_manager_binary()'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_MANAGER_COMMAND=status'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'goal manager compile failed; using validated stale goal manager binary:'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'src/stage1.hello.native.image.json'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'src/stage1.task-workspace-runtime-harness.native.image.json'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" '--force-native-image-refresh'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_IMAGE_SECTION_JOBS: process.env.CLASP_NATIVE_IMAGE_SECTION_JOBS || "1"'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_IMAGE_MODULE_DECL_FRESH_PROCESS:'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE: process.env.CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE || "0"'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_DISABLE_EXPORT_HOST'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_CACHE: "1"'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_DISABLE_SOURCE_EXPORT_CACHE: "1"'
require_pattern "scripts/test-promoted-source-export-cache.sh" 'source-export promoted hit export=nativeImageProjectText'
require_pattern "src/stage1.compiler.source-export-cache-v1.json" '"outputPath": "src/stage1.hello.native.image.json"'
require_pattern "src/stage1.compiler.source-export-cache-v1.json" '"outputPath": "src/stage1.task-workspace-runtime-harness.native.image.json"'
require_pattern "benchmarks/run-benchmark.mjs" 'env.CLASP_CLASPC || env.CLASPC_BIN'
reject_pattern "benchmarks/run-benchmark.mjs" 'unset CLASP_CLASPC CLASPC_BIN'

require_pattern "scripts/test-native-claspc.sh" 'feedback_loop_live_state_root'
require_pattern "scripts/test-native-claspc.sh" 'CLASP_TEST_NATIVE_CLASPC_SHARED_CACHE_HOME'
require_pattern "scripts/test-native-claspc.sh" 'CLASP_TEST_ISOLATED_XDG_CACHE'
require_pattern "scripts/test-native-claspc-smoke.sh" 'test-native-claspc-smoke: ok'
require_pattern "scripts/test-int-builtins.sh" 'test-int-builtins: ok'
require_pattern "scripts/test-dict-builtins.sh" 'test-dict-builtins: ok'
require_pattern "scripts/test-native-runtime-smoke.sh" 'test-native-runtime-smoke: ok'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-claspc-smoke.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-int-builtins.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-dict-builtins.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-runtime-smoke.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-verify-all-smoke.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-claspc.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-runtime.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-verify-all.sh'
require_pattern "scripts/test-native-claspc.sh" 'swarm_loop_builder_running_output'
require_pattern "scripts/test-native-claspc.sh" 'record-ergonomics-app'
require_pattern "scripts/test-native-claspc.sh" 'polymorphism-app'
require_pattern "scripts/test-native-claspc.sh" 'swarm_sqlite_wrong_tool_marker'
require_pattern "scripts/test-native-claspc.sh" 'goal-manager-benchmark-active-resume'
require_pattern "scripts/test-native-claspc.sh" 'goal manager must not complete while a planned task is still active'
require_pattern "scripts/test-native-claspc.sh" 'swarm_sqlite_wrong_completed_verifier_marker'
require_pattern "scripts/test-native-claspc.sh" 'lease is owned by `manager`'
require_pattern "scripts/test-native-claspc.sh" 'lease held by `worker-stale` expired'
require_pattern "scripts/test-native-claspc.sh" 'actor `intruder` is not a swarm manager'
require_pattern "scripts/test-native-claspc.sh" '"deadlineAtMs":4102444800000'
require_pattern "scripts/test-native-claspc.sh" '"mergeDecision":{"taskId":"repair-2","mergegateName":"trunk","verdict":"pass"}'
require_pattern "scripts/test-native-claspc.sh" '"requiredVerifierNames":["native-smoke","native-regression"]'
require_pattern "scripts/test-native-claspc.sh" '"mailboxSummary":{"historyCount":10,"tailCount":10,"approvalCount":0,"runCount":3,"artifactCount":6'
require_pattern "scripts/test-native-claspc.sh" 'assert_native_swarm_verification_trace'
require_pattern "scripts/test-native-claspc.sh" 'entry.failedVerifierClassification === exp.failedVerifierClassification'
require_pattern "scripts/test-native-claspc.sh" 'artifactText(entry.stdoutArtifactPath'
require_pattern "scripts/test-native-claspc.sh" 'lead-app context missing dependencyGraph'
require_pattern "scripts/test-native-claspc.sh" 'dependencyGraph missing Shared.Lead affects edge'
require_pattern "scripts/test-native-claspc.sh" '"mergeReadyRequiredVerifiers":["native-smoke","native-regression"]'
require_pattern "scripts/test-native-claspc.sh" '"failedVerificationPlan":{"objective":"failure-plan","task":"verification-plan-fails","plan":{"name":"focused-native-failure"'
require_pattern "scripts/test-native-claspc.sh" '"passed":false,"failedVerifiers":["native-plan-fail"]'
require_pattern "scripts/test-native-claspc.sh" '"failedPlanRequiredVerifiers":["native-plan-pass","native-plan-fail"],"failedPlanPassed":false,"failedPlanFailedVerifiers":["native-plan-fail"]'

require_pattern "examples/swarm-native/Swarm.clasp" 'objectiveCreateWithDeadline'
require_pattern "examples/swarm-native/Swarm.clasp" 'taskCreateWithDeadline'
require_pattern "examples/swarm-native/Swarm.clasp" 'record VerificationPlan ='
require_pattern "examples/swarm-native/Swarm.clasp" 'record VerificationTraceEntry ='
require_pattern "examples/swarm-native/Swarm.clasp" 'artifactExcerpts : [SwarmArtifactContent]'
require_pattern "examples/swarm-native/Swarm.clasp" 'readArtifactContents handle.root mailboxValue.artifacts contextPackArtifactReadBytes limit'
require_pattern "examples/swarm-native/Swarm.clasp" 'failedVerifierClassification : Str'
require_pattern "examples/swarm-native/Swarm.clasp" 'trace : [VerificationTraceEntry]'
require_pattern "examples/swarm-native/Swarm.clasp" 'verificationTraceEntry verifierName step.run'
require_pattern "examples/swarm-native/Swarm.clasp" 'fold verificationPlanExecutionStep'
require_pattern "examples/swarm-native/Swarm.clasp" 'executeVerificationPlan'
require_pattern "examples/swarm-native/Swarm.clasp" 'policySetForVerificationPlan'
require_pattern "examples/swarm-native/Swarm.clasp" 'approveAndMergeVerificationPlan'
require_pattern "examples/swarm-native/Swarm.clasp" 'memoryLimitMb : Int'
require_pattern "examples/swarm-native/Swarm.clasp" 'toolRunWithLimits : TaskHandle -> SwarmCommand -> Int -> Int -> Result SwarmRun'
require_pattern "examples/swarm-native/Swarm.clasp" 'verifierRunWithLimits : TaskHandle -> Str -> SwarmCommand -> Int -> Int -> Result SwarmRun'
require_pattern "examples/swarm-native/Swarm.clasp" 'toolRunWithOptionalLimits : TaskHandle -> SwarmCommand -> Int -> Int -> Result SwarmRun'
require_pattern "examples/swarm-native/Swarm.clasp" 'executeVerificationPlanWithOptionalLimits : TaskHandle -> VerificationPlan -> Int -> Int -> Int -> Result VerificationPlanResult'
require_pattern "examples/swarm-native/TimedRuns.clasp" 'verifierRunWithLimits taskRef memoryVerifierName memoryCommand 5000 memoryLimitMb'
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASP_LOOP_AGENT_MEMORY_MB_JSON'
require_pattern "examples/swarm-native/GoalManagerServiceMain.clasp" 'CLASP_LOOP_AGENT_MEMORY_MB_JSON'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'CLASP_LOOP_BUILDER_MEMORY_MB_JSON'
require_pattern "scripts/test-goal-manager-default-planner-command.sh" 'CLASP_LOOP_BUILDER_MEMORY_MB_JSON'
require_pattern "examples/swarm-native/Main.clasp" 'objectiveDeadlineAtMs'
require_pattern "examples/swarm-native/Main.clasp" 'repairVerificationPlan'
require_pattern "examples/swarm-native/Main.clasp" 'native-regression'
require_pattern "examples/swarm-native/Main.clasp" 'failedVerificationPlanScenario'
require_pattern "examples/swarm-native/Main.clasp" 'focused-native-failure'
require_pattern "examples/swarm-native/Main.clasp" 'failedPlanFailedVerifiers'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'BenchmarkSignal'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'import Swarm'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'suite = "native-swarm-readiness"'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'objectiveCreateWithDeadline'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'taskCreateWithDeadline'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'policySetForVerificationPlan'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'runToolStepWithTimeout'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'executeVerificationPlanWithTimeout'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'approveAndMergeVerificationPlan'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'taskContextPack'
reject_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'scripts/test-swarm-ready-gate.sh'
require_pattern "runtime/swarm.rs" 'require_active_lease_owner'
require_pattern "runtime/swarm.rs" 'require_unexpired_lease_owner'
require_pattern "runtime/swarm.rs" 'require_recorded_lease_owner'
require_pattern "runtime/swarm.rs" 'require_manager_actor'
require_pattern "runtime/swarm.rs" 'builtin_swarm_objective_create_with_deadline'
require_pattern "runtime/swarm.rs" 'builtin_swarm_task_create_with_deadline'
require_pattern "runtime/swarm.rs" '--memory-mb'
require_pattern "runtime/swarm.rs" 'memoryLimitMb'
require_pattern "runtime/swarm.rs" 'apply_virtual_memory_limit'
require_pattern "runtime/swarm.rs" 'swarm_tool_run_enforces_memory_limit_and_records_it'
require_pattern "runtime/swarm.rs" 'DEFAULT_SWARM_OUTPUT_LIMIT_BYTES'
require_pattern "runtime/swarm.rs" 'run_command_to_artifacts'
require_pattern "runtime/swarm.rs" 'stdoutTruncated'
require_pattern "runtime/swarm.rs" 'swarm_run_output_artifacts_are_bounded'
reject_pattern "runtime/swarm.rs" '.output()'
require_pattern "scripts/test-native-claspc.sh" 'swarm_sqlite_output_limit_output'
require_pattern "scripts/test-native-claspc.sh" '"stdoutTruncated":true'
