#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require_pattern() {
  local path="$1"
  local pattern="$2"

  if ! grep -F -- "$pattern" "$project_root/$path" >/dev/null; then
    printf 'missing swarm-ready gate pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
}

reject_pattern() {
  local path="$1"
  local pattern="$2"

  if grep -F -- "$pattern" "$project_root/$path" >/dev/null; then
    printf 'unexpected swarm-ready gate pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
}

bash -n "$project_root/scripts/test-native-claspc.sh" "$project_root/scripts/test-native-claspc-smoke.sh" "$project_root/scripts/test-native-runtime-smoke.sh" "$project_root/scripts/test-verify-all-smoke.sh" "$project_root/scripts/test-agent-command-template.sh" "$project_root/scripts/test-goal-manager-agent-command-template.sh"
bash -n "$project_root/scripts/test-goal-manager-planner-report-decode.sh"
bash -n "$project_root/examples/swarm-kernel/scripts/verify.sh"
node "$project_root/scripts/check-promoted-native-image-exports.mjs" >/dev/null

require_pattern "examples/feedback-loop/Main.clasp" 'codexModel = readEnvText "CLASP_LOOP_CODEX_MODEL_JSON" (readEnvText "CLASP_LOOP_AGENT_MODEL_JSON" "gpt-5.5")'
require_pattern "examples/feedback-loop/Main.clasp" 'codexReasoning = readEnvText "CLASP_LOOP_CODEX_REASONING_JSON" (readEnvText "CLASP_LOOP_AGENT_REASONING_JSON" "xhigh")'
require_pattern "examples/feedback-loop/Main.clasp" 'agentCommandTemplate = readEnvCommandTextList "CLASP_LOOP_AGENT_COMMAND_JSON" emptyTexts'
require_pattern "examples/feedback-loop/Main.clasp" 'renderAgentCommand role schemaPath reportPath promptPath'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'codexModel = readEnvText "CLASP_LOOP_CODEX_MODEL_JSON" (readEnvText "CLASP_LOOP_AGENT_MODEL_JSON" "gpt-5.5")'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'codexReasoning = readEnvText "CLASP_LOOP_CODEX_REASONING_JSON" (readEnvText "CLASP_LOOP_AGENT_REASONING_JSON" "xhigh")'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'plannerAgentCommandTemplate = readEnvTextList "CLASP_MANAGER_PLANNER_AGENT_COMMAND_JSON" agentCommandTemplate'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'plannerAgentCommandArgs'
require_pattern "scripts/test-agent-command-template.sh" 'agent-command-template-ok'
require_pattern "scripts/test-agent-command-template.sh" 'native-provider-neutral-agent-template-ok'
require_pattern "scripts/test-agent-command-template.sh" 'CLASP_AGENT_COMMAND_TEMPLATE_NATIVE'
require_pattern "scripts/test-agent-command-template.sh" 'examples/swarm-native/FeedbackLoop.clasp'
require_pattern "scripts/verify-all.sh" 'CLASP_AGENT_COMMAND_TEMPLATE_FEEDBACK=0 CLASP_AGENT_COMMAND_TEMPLATE_NATIVE=1 bash scripts/test-agent-command-template.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-goal-manager-agent-command-template.sh'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'goal-manager-agent-command-template-ok'
require_pattern "scripts/test-goal-manager-agent-command-template.sh" 'Codex fallback backend should not be invoked'
require_pattern "examples/feedback-loop/Main.clasp" 'watchModeEnabled'
require_pattern "examples/feedback-loop/Main.clasp" '"builder-running"'
require_pattern "examples/feedback-loop/Main.clasp" '"verifier-running"'
require_pattern "examples/feedback-loop/Main.clasp" 'Verification tier: focused.'
require_pattern "examples/feedback-loop/Main.clasp" 'Do not run `bash scripts/verify-all.sh` for this focused branch.'
require_pattern "examples/feedback-loop/Main.clasp" 'CLASP_LOOP_FOCUSED_VERIFIER_TIMEOUT_MS_JSON'
require_pattern "examples/feedback-loop/Main.clasp" 'ensureStepReportWithTimeout'
require_pattern "examples/feedback-loop/Main.clasp" 'diff -ruN '
require_pattern "examples/feedback-loop/Main.clasp" 'verifierShellCommand'
require_pattern "examples/feedback-loop/Main.clasp" 'CLASP_LOOP_BASELINE_WORKSPACE_JSON'
require_pattern "examples/feedback-loop/Main.clasp" 'focusedVerifySelectionPath'
require_pattern "examples/feedback-loop/Main.clasp" 'Focused verification command source: '
require_pattern "examples/feedback-loop/Main.clasp" 'import FocusedSelection'
require_pattern "examples/feedback-loop/FocusedSelection.clasp" 'bash scripts/verify-fast.sh'
require_pattern "examples/feedback-loop/FocusedSelection.clasp" 'bash scripts/test-feedback-loop-routing.sh loop-routing'
require_pattern "scripts/test-feedback-loop-routing.sh" 'FocusedSelectionProbe.clasp'
reject_pattern "examples/feedback-loop/Main.clasp" '"file: workspace.txt"'
reject_pattern "examples/feedback-loop/Main.clasp" '"--exclude=workspace.txt "'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-feedback-loop-resume.sh'
require_pattern "scripts/test-feedback-loop-resume.sh" 'CLASP_TEST_SHARED_XDG_CACHE_HOME'
require_pattern "scripts/test-feedback-loop-resume.sh" 'CLASP_TEST_ISOLATED_XDG_CACHE'
require_pattern "examples/feedback-loop/Process.clasp" 'awaitWatchedProcessTimeoutJson'
require_pattern "examples/feedback-loop/MonitoredWorkflowDemo.clasp" 'workflow-status.json'
require_pattern "examples/feedback-loop/MonitoredWorkflowDemo.clasp" 'failure-detected'
require_pattern "examples/feedback-loop/MonitoredWorkflowDemo.clasp" '"failed-handled"'
require_pattern "examples/feedback-loop/CodexLoopDemo.clasp" 'ordinary-clasp-codex-loop'
require_pattern "examples/feedback-loop/CodexLoopDemo.clasp" 'codex-loop-status.json'
require_pattern "examples/feedback-loop/CodexLoopDemo.clasp" 'codexExecCommand'
require_pattern "scripts/test-codex-loop-program.sh" 'codex-loop-program-ok'
require_pattern "examples/swarm-native/GoalManager.clasp" 'heartbeatTaskLease'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_PLANNER_POLICY_JSON'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_TASK_WORKSPACE_ROOT_JSON'
require_pattern "examples/swarm-native/GoalManager.clasp" 'CLASP_MANAGER_TASK_PROMOTION_HEARTBEAT_JSON'
require_pattern "examples/swarm-native/GoalManagerServiceMain.clasp" 'CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON='
require_pattern "examples/swarm-native/GoalManager.clasp" 'planner external resource blocked'
require_pattern "examples/swarm-native/GoalManager.clasp" 'external-resource-blocker'
require_pattern "examples/swarm-native/GoalManager.clasp" 'Do not inspect files, run shell commands, invoke tools, or gather extra repository context from the planner.'
require_pattern "examples/swarm-native/GoalManager.clasp" 'Return the final planner-report JSON immediately; do not stream interim plans or empty task lists.'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'Do not inspect files, run shell commands, invoke tools, or gather extra repository context from the planner.'
require_pattern "examples/swarm-native/GoalManagerBootstrapPlanner.clasp" 'Return the final planner-report JSON immediately; do not stream interim plans or empty task lists.'
require_pattern "examples/swarm-native/GoalManager.clasp" 'already exists'
require_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '--exclude=libclasp_runtime.a'
require_pattern "examples/swarm-native/GoalManagerPrelude.clasp" 'repairPromotedNativeWorkspaceArtifacts'
require_pattern "examples/swarm-native/GoalManagerBootstrapSetup.clasp" 'workspace-artifact-error'
require_pattern "examples/swarm-native/GoalManagerTaskWorkspaceRuntime.clasp" 'task workspace artifact repair failed'
reject_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '--exclude=src/stage1*.native.image.json'
reject_pattern "examples/swarm-native/GoalManagerPrelude.clasp" '--exclude=src/embedded*.native.image.json'
reject_pattern "examples/swarm-native/GoalManager.clasp" '--exclude=src/stage1*.native.image.json'
reject_pattern "examples/swarm-native/GoalManager.clasp" '--exclude=src/embedded*.native.image.json'
require_pattern "examples/swarm-native/GoalManager.clasp" 'plannerReportFromRaw : Str -> Result PlannerReport'
require_pattern "examples/swarm-native/GoalManager.clasp" 'planner report missing required fields'
require_pattern "examples/swarm-native/GoalManagerReportIO.clasp" 'plannerReportFromRaw : Str -> Result PlannerReport'
require_pattern "examples/swarm-native/PlannerReportDecodeHarness.clasp" 'malformed-empty-tasks'
require_pattern "examples/swarm-native/PlannerReportDecodeHarness.clasp" '{\"tasks\":[]}'
require_pattern "examples/swarm-native/PlannerReportDecodeHarness.clasp" 'legacy-task'
require_pattern "scripts/test-goal-manager-planner-report-decode.sh" 'current-empty-tasks=ok:0:current empty'
reject_pattern "examples/swarm-native/GoalManager.clasp" 'plannerReportFromRaw : Str -> PlannerReport'
reject_pattern "examples/swarm-native/GoalManagerReportIO.clasp" 'plannerReportFromRaw : Str -> PlannerReport'
reject_pattern "examples/swarm-native/GoalManager.scratch.clasp" 'plannerReportFromRaw : Str -> PlannerReport'
require_pattern "runtime/claspc.rs" 'embedded_final_status_output'
require_pattern "runtime/clasp_runtime.rs" 'finalStatusPath'
require_pattern "scripts/test-goal-manager-fast.sh" 'runtime failed to execute native compiler export'
require_pattern "scripts/test-goal-manager-fast.sh" 'CLASP_TEST_FAKE_PLANNER_USAGE_LIMIT_FAILS'
require_pattern "scripts/test-goal-manager-fast.sh" 'CLASP_TEST_FAKE_PLANNER_MALFORMED_REPORT'
require_pattern "scripts/test-goal-manager-fast.sh" 'malformed planner report should not crash the native export boundary'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'childLoopAwaitTimeoutMs = readEnvInt "CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON" 10000'
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASP_MANAGER_CHILD_AWAIT_TIMEOUT_MS_JSON='
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitor.clasp" 'heartbeatTaskLease'
require_pattern "examples/swarm-native/GoalManagerTaskExecutionHelpers.clasp" 'recoverExpiredTaskFailureRecording'
require_pattern "examples/swarm-native/GoalManagerWatch.clasp" 'awaitWatchedProcessTimeout'
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitor.clasp" 'awaitChildLoopOutcome'
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitor.clasp" 'monitoredLoopAwait'
require_pattern "examples/swarm-native/GoalManagerWatch.clasp" 'if message == "timeout" then'
require_pattern "examples/swarm-native/GoalManagerWatch.clasp" 'reconcileWatchedProcess heartbeatPath'
require_pattern "scripts/test-goal-manager-fast.sh" "CLASP_MANAGER_TASK_WORKSPACE_CACHE_MAX_MB_JSON='16'"
require_pattern "examples/swarm-native/GoalManagerBenchmarkCommand.clasp" 'benchmarkDefaultPassSignal'
require_pattern "examples/swarm-native/GoalManagerBenchmarkCommand.clasp" 'benchmark command passed without signal'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" 'record MonitoredLoopOutcome'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"completed-pass"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"completed-fail"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"missing-heartbeat"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"malformed-unresolved-heartbeat"'
require_pattern "examples/swarm-native/GoalManagerMonitoredLoop.clasp" '"retry-exhausted"'
require_pattern "examples/swarm-native/GoalManagerTaskStatusRuntime.clasp" 'childLoopLaunchOutcome'
require_pattern "examples/swarm-native/MonitoredLoopHarness.clasp" 'monitoredLoopSpawn'
require_pattern "examples/swarm-native/MonitoredLoopHarness.clasp" 'monitoredLoopLaunchOrResume'
require_pattern "examples/swarm-native/GoalManagerChildLoopMonitorHarness.clasp" 'retryRecoveryWaitingReasonForTask'
require_pattern "examples/swarm-native/GoalManagerChildLoopControlHarness.clasp" 'objectiveCreate controlRoot'
require_pattern "examples/swarm-native/GoalManagerChildLoopControlHarness.clasp" 'awaitWatchedProcessTimeoutRaw'
require_pattern "scripts/test-monitored-loop.sh" 'retry-exhausted=retry-exhausted'
require_pattern "scripts/test-monitored-loop.sh" 'watch-pass=completed-pass'
require_pattern "scripts/test-goal-manager-child-loop-monitor.sh" 'lease-await=timeout'
require_pattern "scripts/test-goal-manager-child-loop-monitor.sh" 'lease-heartbeat-seen=true'
require_pattern "scripts/test-goal-manager-child-loop-monitor.sh" 'goal-manager-child-loop-monitor-ok'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-monitored-loop.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-monitored-workflow.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-codex-loop-program.sh'
require_pattern "scripts/verify-all.sh" 'bash scripts/test-goal-manager-child-loop-monitor.sh'
require_pattern "scripts/run-managed-job.sh" 'exit-status'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_TOKEN'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_STOP_REQUEST'
require_pattern "scripts/run-managed-job.sh" 'CLASP_MANAGED_JOB_MEMORY_MB'
require_pattern "scripts/run-managed-job.sh" 'stop-request-path'
require_pattern "scripts/run-managed-job.sh" 'session_rss_kb'
require_pattern "scripts/run-managed-job.sh" 'memory-exceeded'
require_pattern "scripts/stop-managed-job.sh" 'stop-requested'
require_pattern "scripts/stop-managed-job.sh" '--force-signal'
require_pattern "scripts/stop-managed-job.sh" 'marked_session_pids'
require_pattern "scripts/stop-managed-job.sh" 'refusing to stop unmarked session members'
require_pattern "scripts/test-managed-job.sh" 'complete-smoke'
require_pattern "scripts/test-managed-job.sh" 'forged-unmarked-session'
require_pattern "scripts/test-managed-job.sh" 'memory-watch-smoke'
require_pattern "scripts/clasp-codex-loop-start.sh" 'run-managed-job.sh'
require_pattern "scripts/clasp-codex-loop-stop.sh" 'stop-managed-job.sh'
require_pattern "scripts/clasp-codex-loop-stop.sh" 'refusing to signal without managed-job metadata'
require_pattern "scripts/clasp-swarm-start.sh" 'run-managed-job.sh'
require_pattern "scripts/clasp-swarm-stop.sh" 'stop-managed-job.sh'
require_pattern "scripts/clasp-swarm-stop.sh" 'refusing to signal without managed-job metadata'
require_pattern "scripts/clasp-autopilot-start.sh" 'run-managed-job.sh'
require_pattern "scripts/clasp-autopilot-stop.sh" 'stop-managed-job.sh'
require_pattern "scripts/clasp-autopilot-stop.sh" 'refusing to signal without managed-job metadata'
reject_pattern "scripts/clasp-codex-loop-stop.sh" 'kill -TERM -- "-\$pid"'
reject_pattern "scripts/clasp-codex-loop-stop.sh" 'kill -KILL -- "-\$pid"'
reject_pattern "scripts/clasp-swarm-stop.sh" 'kill_descendants'
reject_pattern "scripts/clasp-swarm-stop.sh" 'kill -9'
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASPC_BIN='
require_pattern "examples/swarm-native/GoalManagerBootstrapTasks.clasp" 'CLASP_CLASPC='
require_pattern "examples/swarm-native/GoalManager.clasp" 'recoverExpiredTaskFailureRecording'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" 'childFocusedVerifyCommands'
require_pattern "examples/swarm-native/GoalManagerConfig.clasp" '    ""'
reject_pattern "examples/swarm-native/GoalManagerConfig.clasp" '    "bash scripts/test-goal-manager-fast.sh\nbash scripts/test-native-runtime.sh\nbash scripts/test-task-manifest.sh"'
reject_pattern "examples/swarm-native/GoalManager.clasp" '    "bash scripts/test-goal-manager-fast.sh\nbash scripts/test-native-runtime.sh\nbash scripts/test-task-manifest.sh"'

require_pattern "scripts/test-selfhost.sh" 'generate-promoted-module-summary-cache.mjs" --check'
require_pattern "scripts/test-selfhost.sh" 'CLASP_TEST_SELFHOST_SHARED_CACHE_HOME'
require_pattern "scripts/test-selfhost.sh" 'CLASP_TEST_ISOLATED_XDG_CACHE'
require_pattern "scripts/test-selfhost.sh" 'check-promoted-native-image-exports.mjs'
require_pattern "scripts/test-selfhost.sh" 'contextSourceText'
require_pattern "scripts/test-selfhost.sh" 'surfaceIndex'
require_pattern "scripts/test-selfhost.sh" 'clasp-dependency-graph-v1'
require_pattern "scripts/test-selfhost.sh" 'dependencyGraph missing Main -> Shared.Lead import edge'
require_pattern "scripts/test-selfhost.sh" 'mockLeadSummaryModel'
require_pattern "scripts/test-selfhost.sh" 'module-summary (promoted )?hit module=Compiler\.Ast'
require_pattern "scripts/test-selfhost.sh" 'module-summary (promoted )?hit module=Compiler\.Emit\.JavaScript'
require_pattern "scripts/test-selfhost.sh" 'module-summary (promoted )?hit module=Main'
require_pattern "scripts/verify-fast.sh" 'bash src/scripts/verify.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-selfhost.sh'
require_pattern "runtime/claspc.rs" 'stage1.compiler.module-summary-cache-v2.json'
require_pattern "runtime/claspc.rs" 'read_promoted_module_summary'
require_pattern "runtime/claspc.rs" 'promoted_module_summary_cache_text'
require_pattern "runtime/claspc.rs" 'Persist inside the worker so an outer timeout still preserves'
require_pattern "runtime/claspc.rs" 'decl-module-context-v2'
require_pattern "runtime/claspc.rs" 'augment_context_dependency_graph_output'
require_pattern "runtime/claspc.rs" 'clasp-dependency-graph-v1'
require_pattern "runtime/claspc.rs" 'decl-module summary-plan skipped; all chunk modules cached'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_BUILD_PLAN_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_DECL_MODULE_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_CACHE'
require_pattern "runtime/claspc.rs" 'CLASP_NATIVE_DISABLE_SOURCE_EXPORT_CACHE'
require_pattern "runtime/claspc.rs" 'source-export promoted output-path hit'
require_pattern "runtime/claspc.rs" 'read_cached_source_export(image_path, NATIVE_IMAGE_MONOLITHIC_EXPORT'
reject_pattern "scripts/resolve-claspc.sh" 'stage1.compiler.module-summary-cache-v2.json" -nt "$binary_path"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'goal_manager_relaxed_build_plan_cache="${CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE:-1}"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_PROJECT_ROOT="$project_root"'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'validate_stale_goal_manager_binary()'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'CLASP_MANAGER_COMMAND=status'
require_pattern "scripts/ensure-goal-manager-binary.sh" 'goal manager compile failed; using validated stale goal manager binary:'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'src/stage1.hello.native.image.json'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'src/stage1.goal-manager.native.image.json'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'src/stage1.task-workspace-runtime-harness.native.image.json'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" '--force-native-image-refresh'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_IMAGE_SECTION_JOBS: process.env.CLASP_NATIVE_IMAGE_SECTION_JOBS || "1"'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE: process.env.CLASP_NATIVE_RELAXED_BUILD_PLAN_CACHE || "0"'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_DISABLE_EXPORT_HOST'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_DISABLE_NATIVE_IMAGE_CACHE: "1"'
require_pattern "scripts/generate-promoted-source-export-cache.mjs" 'CLASP_NATIVE_DISABLE_SOURCE_EXPORT_CACHE: "1"'
require_pattern "scripts/test-promoted-source-export-cache.sh" 'source-export promoted hit export=nativeImageProjectText'
require_pattern "src/stage1.compiler.source-export-cache-v1.json" '"outputPath": "src/stage1.hello.native.image.json"'
require_pattern "src/stage1.compiler.source-export-cache-v1.json" '"outputPath": "src/stage1.goal-manager.native.image.json"'
require_pattern "src/stage1.compiler.source-export-cache-v1.json" '"outputPath": "src/stage1.task-workspace-runtime-harness.native.image.json"'
require_pattern "benchmarks/run-benchmark.mjs" 'env.CLASP_CLASPC || env.CLASPC_BIN'
reject_pattern "benchmarks/run-benchmark.mjs" 'unset CLASP_CLASPC CLASPC_BIN'

require_pattern "scripts/test-native-claspc.sh" 'feedback_loop_live_state_root'
require_pattern "scripts/test-native-claspc.sh" 'CLASP_TEST_NATIVE_CLASPC_SHARED_CACHE_HOME'
require_pattern "scripts/test-native-claspc.sh" 'CLASP_TEST_ISOLATED_XDG_CACHE'
require_pattern "scripts/test-native-claspc-smoke.sh" 'test-native-claspc-smoke: ok'
require_pattern "scripts/test-native-runtime-smoke.sh" 'test-native-runtime-smoke: ok'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-claspc-smoke.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-runtime-smoke.sh'
require_pattern "scripts/verify-fast.sh" 'bash scripts/test-verify-all-smoke.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-claspc.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-native-runtime.sh'
reject_pattern "scripts/verify-fast.sh" 'bash scripts/test-verify-all.sh'
require_pattern "scripts/test-native-claspc.sh" 'swarm_loop_builder_running_output'
require_pattern "scripts/test-native-claspc.sh" 'record-ergonomics-app'
require_pattern "scripts/test-native-claspc.sh" 'polymorphism-app'
require_pattern "scripts/test-native-claspc.sh" 'swarm_sqlite_wrong_tool_marker'
require_pattern "scripts/test-native-claspc.sh" 'goal-manager-benchmark-active-resume'
require_pattern "scripts/test-native-claspc.sh" 'goal manager must not complete while a planned task is still active'
require_pattern "scripts/test-native-claspc.sh" 'swarm_sqlite_wrong_completed_verifier_marker'
require_pattern "scripts/test-native-claspc.sh" 'lease is owned by `manager`'
require_pattern "scripts/test-native-claspc.sh" 'lease held by `worker-stale` expired'
require_pattern "scripts/test-native-claspc.sh" 'actor `intruder` is not a swarm manager'
require_pattern "scripts/test-native-claspc.sh" '"deadlineAtMs":4102444800000'
require_pattern "scripts/test-native-claspc.sh" '"mergeDecision":{"taskId":"repair-2","mergegateName":"trunk","verdict":"pass"}'
require_pattern "scripts/test-native-claspc.sh" '"requiredVerifierNames":["native-smoke","native-regression"]'
require_pattern "scripts/test-native-claspc.sh" '"mailboxSummary":{"historyCount":10,"tailCount":10,"approvalCount":0,"runCount":3,"artifactCount":6'
require_pattern "scripts/test-native-claspc.sh" 'assert_native_swarm_verification_trace'
require_pattern "scripts/test-native-claspc.sh" 'entry.failedVerifierClassification === exp.failedVerifierClassification'
require_pattern "scripts/test-native-claspc.sh" 'artifactText(entry.stdoutArtifactPath'
require_pattern "scripts/test-native-claspc.sh" 'lead-app context missing dependencyGraph'
require_pattern "scripts/test-native-claspc.sh" 'dependencyGraph missing Shared.Lead affects edge'
require_pattern "scripts/test-native-claspc.sh" '"mergeReadyRequiredVerifiers":["native-smoke","native-regression"]'
require_pattern "scripts/test-native-claspc.sh" '"failedVerificationPlan":{"objective":"failure-plan","task":"verification-plan-fails","plan":{"name":"focused-native-failure"'
require_pattern "scripts/test-native-claspc.sh" '"passed":false,"failedVerifiers":["native-plan-fail"]'
require_pattern "scripts/test-native-claspc.sh" '"failedPlanRequiredVerifiers":["native-plan-pass","native-plan-fail"],"failedPlanPassed":false,"failedPlanFailedVerifiers":["native-plan-fail"]'

require_pattern "examples/swarm-native/Swarm.clasp" 'objectiveCreateWithDeadline'
require_pattern "examples/swarm-native/Swarm.clasp" 'taskCreateWithDeadline'
require_pattern "examples/swarm-native/Swarm.clasp" 'record VerificationPlan ='
require_pattern "examples/swarm-native/Swarm.clasp" 'record VerificationTraceEntry ='
require_pattern "examples/swarm-native/Swarm.clasp" 'failedVerifierClassification : Str'
require_pattern "examples/swarm-native/Swarm.clasp" 'trace : [VerificationTraceEntry]'
require_pattern "examples/swarm-native/Swarm.clasp" 'verificationTraceEntry verifierName step.run'
require_pattern "examples/swarm-native/Swarm.clasp" 'fold verificationPlanExecutionStep'
require_pattern "examples/swarm-native/Swarm.clasp" 'executeVerificationPlan'
require_pattern "examples/swarm-native/Swarm.clasp" 'policySetForVerificationPlan'
require_pattern "examples/swarm-native/Swarm.clasp" 'approveAndMergeVerificationPlan'
require_pattern "examples/swarm-native/Main.clasp" 'objectiveDeadlineAtMs'
require_pattern "examples/swarm-native/Main.clasp" 'repairVerificationPlan'
require_pattern "examples/swarm-native/Main.clasp" 'native-regression'
require_pattern "examples/swarm-native/Main.clasp" 'failedVerificationPlanScenario'
require_pattern "examples/swarm-native/Main.clasp" 'focused-native-failure'
require_pattern "examples/swarm-native/Main.clasp" 'failedPlanFailedVerifiers'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'BenchmarkSignal'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'scripts/test-swarm-ready-gate.sh'
require_pattern "examples/swarm-native/SwarmReadyBenchmark.clasp" 'suite = "swarm-ready-gate"'
require_pattern "runtime/swarm.rs" 'require_active_lease_owner'
require_pattern "runtime/swarm.rs" 'require_unexpired_lease_owner'
require_pattern "runtime/swarm.rs" 'require_recorded_lease_owner'
require_pattern "runtime/swarm.rs" 'require_manager_actor'
require_pattern "runtime/swarm.rs" 'builtin_swarm_objective_create_with_deadline'
require_pattern "runtime/swarm.rs" 'builtin_swarm_task_create_with_deadline'
