#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_root="${CLASP_TEST_TMPDIR:-${TMPDIR:-/tmp}}"
mkdir -p "$tmp_root"
test_root="$(mktemp -d "$tmp_root/test-native-claspc-smoke.XXXXXX")"

cleanup() {
  rm -rf "$test_root"
}

trap cleanup EXIT

shared_cache_root="${CLASP_TEST_NATIVE_CLASPC_SHARED_CACHE_HOME:-${CLASP_TEST_SHARED_XDG_CACHE_HOME:-$tmp_root/clasp-test-xdg-cache}}"
if [[ "${CLASP_TEST_ISOLATED_XDG_CACHE:-0}" == "1" ]]; then
  shared_cache_root="$test_root/xdg-cache"
fi
export XDG_CACHE_HOME="$shared_cache_root/native-claspc-smoke"
mkdir -p "$XDG_CACHE_HOME"

claspc_bin="$(env -u CLASP_CLASPC -u CLASPC_BIN "$project_root/scripts/resolve-claspc.sh")"
hello_output="$test_root/hello.mjs"
cli_source="$test_root/CliSmoke.clasp"
cli_binary="$test_root/cli-smoke"
cli_output="$test_root/argv.txt"
polymorphism_binary="$test_root/polymorphism-smoke"

"$claspc_bin" --json check "$project_root/examples/hello.clasp" | grep -F '"status":"ok"' >/dev/null
"$claspc_bin" compile "$project_root/examples/hello.clasp" -o "$hello_output"
grep -F '// Generated by compiler-selfhost' "$hello_output" >/dev/null

cat >"$cli_source" <<EOF
module Main

main : Str
main = match writeFile "$(printf '%s' "$cli_output")" (textJoin "," argv) {
  Ok written -> textJoin "," argv,
  Err message -> message
}
EOF

env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$cli_source" -o "$cli_binary"
[[ -x "$cli_binary" ]]
"$cli_binary" alpha beta | grep -Fx 'alpha,beta' >/dev/null
grep -Fx 'alpha,beta' "$cli_output" >/dev/null

"$claspc_bin" --json check "$project_root/examples/polymorphism/Main.clasp" | grep -F '"status":"ok"' >/dev/null
env RUSTC=/definitely-missing-rustc "$claspc_bin" compile "$project_root/examples/polymorphism/Main.clasp" -o "$polymorphism_binary"
[[ -x "$polymorphism_binary" ]]
"$polymorphism_binary" | grep -Fx 'ok|true|true|true' >/dev/null

native_list_dir_output="$(
  timeout 90 "$claspc_bin" run "$project_root/examples/native-list-dir/Main.clasp" -- "$project_root/examples/native-list-dir/fixture"
)"
printf '%s\n' "$native_list_dir_output" | grep -Fx 'alpha.txt,beta.txt|ERR:missing' >/dev/null

printf 'test-native-claspc-smoke: ok\n'
