#!/usr/bin/env bash
set -euo pipefail

project_root="${CLASP_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
example_root="$project_root/examples/compiler-selfhost"
compiled_path="$example_root/compiled.mjs"
emitted_path="$example_root/emitted.mjs"

cleanup() {
  rm -f "$compiled_path" "$emitted_path"
}

trap cleanup EXIT

run_verify() {
  cd "$project_root"
  cabal run claspc -- check examples/compiler-selfhost/Main.clasp
  cabal run claspc -- compile examples/compiler-selfhost/Main.clasp -o "$compiled_path"
  bun examples/compiler-selfhost/demo.mjs "$compiled_path" "$emitted_path"
}

if [[ -n "${IN_NIX_SHELL:-}" ]]; then
  run_verify | tail -n 1 | grep -F '{"loweredValue":"const greeting = literal:hello","loweredFunction":"function renderLead(lead) = call String(lead)","loweredModule":"const greeting = literal:hello\nfunction renderLead(lead) = call String(lead)","checkedValueType":"Str","checkedFunctionType":"Int -> Str","checkedModule":"greeting : Str\nrenderLead : Int -> Str","mismatchDiagnostic":"Type mismatch for `greeting`: expected Int, found Str.","emittedModule":"// Generated by compiler-selfhost\nexport const greeting = \"hello\";\nexport function renderLead(lead) { return String(lead); }","emittedGreeting":"hello","emittedRender":"42"}'
else
  nix develop "$project_root" --command bash -lc "
    set -euo pipefail
    export CLASP_PROJECT_ROOT=\"$project_root\"
    bash examples/compiler-selfhost/scripts/verify.sh
  "
fi
